/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mariem_1 (void)
{
  GtkWidget *mariem_1;
  GtkWidget *fixed1MM;
  GtkWidget *treeview1MM;
  GtkWidget *vscrollbar1;
  GtkWidget *label1MM;
  GtkWidget *label2MM;
  GtkWidget *button2MM;
  GtkWidget *button3MM;
  GtkWidget *button4MM;
  GtkWidget *button1MM;

  mariem_1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mariem_1), _("affichage bureaux du votes"));

  fixed1MM = gtk_fixed_new ();
  gtk_widget_show (fixed1MM);
  gtk_container_add (GTK_CONTAINER (mariem_1), fixed1MM);

  treeview1MM = gtk_tree_view_new ();
  gtk_widget_show (treeview1MM);
  gtk_fixed_put (GTK_FIXED (fixed1MM), treeview1MM, 136, 80);
  gtk_widget_set_size_request (treeview1MM, 300, 200);

  vscrollbar1 = gtk_vscrollbar_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 0, 0, 0, 0)));
  gtk_widget_show (vscrollbar1);
  gtk_fixed_put (GTK_FIXED (fixed1MM), vscrollbar1, 440, 104);
  gtk_widget_set_size_request (vscrollbar1, 16, 176);

  label1MM = gtk_label_new (_("gestion des bureaux du votes"));
  gtk_widget_show (label1MM);
  gtk_fixed_put (GTK_FIXED (fixed1MM), label1MM, 152, 16);
  gtk_widget_set_size_request (label1MM, 240, 24);

  label2MM = gtk_label_new (_("liste des bureaux du votes"));
  gtk_widget_show (label2MM);
  gtk_fixed_put (GTK_FIXED (fixed1MM), label2MM, 168, 40);
  gtk_widget_set_size_request (label2MM, 216, 16);

  button2MM = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (button2MM);
  gtk_fixed_put (GTK_FIXED (fixed1MM), button2MM, 112, 320);
  gtk_widget_set_size_request (button2MM, 80, 24);

  button3MM = gtk_button_new_with_mnemonic (_("modifier "));
  gtk_widget_show (button3MM);
  gtk_fixed_put (GTK_FIXED (fixed1MM), button3MM, 232, 320);
  gtk_widget_set_size_request (button3MM, 128, 24);

  button4MM = gtk_button_new_with_mnemonic (_("supprimer "));
  gtk_widget_show (button4MM);
  gtk_fixed_put (GTK_FIXED (fixed1MM), button4MM, 416, 320);
  gtk_widget_set_size_request (button4MM, 112, 24);

  button1MM = gtk_button_new_with_mnemonic (_("retour "));
  gtk_widget_show (button1MM);
  gtk_fixed_put (GTK_FIXED (fixed1MM), button1MM, 16, 344);
  gtk_widget_set_size_request (button1MM, 72, 24);

  g_signal_connect ((gpointer) button2MM, "clicked",
                    G_CALLBACK (on_button2MM_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3MM, "clicked",
                    G_CALLBACK (on_button3MM_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4MM, "clicked",
                    G_CALLBACK (on_button4MM_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mariem_1, mariem_1, "mariem_1");
  GLADE_HOOKUP_OBJECT (mariem_1, fixed1MM, "fixed1MM");
  GLADE_HOOKUP_OBJECT (mariem_1, treeview1MM, "treeview1MM");
  GLADE_HOOKUP_OBJECT (mariem_1, vscrollbar1, "vscrollbar1");
  GLADE_HOOKUP_OBJECT (mariem_1, label1MM, "label1MM");
  GLADE_HOOKUP_OBJECT (mariem_1, label2MM, "label2MM");
  GLADE_HOOKUP_OBJECT (mariem_1, button2MM, "button2MM");
  GLADE_HOOKUP_OBJECT (mariem_1, button3MM, "button3MM");
  GLADE_HOOKUP_OBJECT (mariem_1, button4MM, "button4MM");
  GLADE_HOOKUP_OBJECT (mariem_1, button1MM, "button1MM");

  return mariem_1;
}

GtkWidget*
create_mariem2 (void)
{
  GtkWidget *mariem2;
  GtkWidget *fixed2MM;
  GtkWidget *entry1MM;
  GtkWidget *entry2MM;
  GtkWidget *label6;
  GtkObject *spinbutton1MM_adj;
  GtkWidget *spinbutton1MM;
  GtkWidget *entry3MM;
  GtkWidget *label3MM;
  GtkWidget *label5MM;
  GtkWidget *label7MM;
  GtkWidget *label8MM;
  GtkWidget *label9MM;
  GtkWidget *label10MM;
  GtkWidget *label11MM;
  GtkWidget *label4MM;
  GtkWidget *checkbutton1MM;
  GtkWidget *checkbutton2MM;
  GtkWidget *checkbutton3MM;
  GtkWidget *radiobutton1MM;
  GSList *radiobutton1MM_group = NULL;
  GtkWidget *radiobutton2MM;
  GtkWidget *combobox4MM;
  GtkWidget *button6MM;
  GtkWidget *button5MM;

  mariem2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mariem2), _("ajout bureau de vote"));

  fixed2MM = gtk_fixed_new ();
  gtk_widget_show (fixed2MM);
  gtk_container_add (GTK_CONTAINER (mariem2), fixed2MM);

  entry1MM = gtk_entry_new ();
  gtk_widget_show (entry1MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), entry1MM, 176, 56);
  gtk_widget_set_size_request (entry1MM, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1MM), 8226);

  entry2MM = gtk_entry_new ();
  gtk_widget_show (entry2MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), entry2MM, 176, 96);
  gtk_widget_set_size_request (entry2MM, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2MM), 8226);

  label6 = gtk_label_new ("");
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label6, 24, 144);
  gtk_widget_set_size_request (label6, 41, 17);

  spinbutton1MM_adj = gtk_adjustment_new (1, 1, 5, 1, 10, 10);
  spinbutton1MM = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1MM_adj), 1, 0);
  gtk_widget_show (spinbutton1MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), spinbutton1MM, 192, 256);
  gtk_widget_set_size_request (spinbutton1MM, 60, 27);

  entry3MM = gtk_entry_new ();
  gtk_widget_show (entry3MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), entry3MM, 176, 144);
  gtk_widget_set_size_request (entry3MM, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3MM), 8226);

  label3MM = gtk_label_new (_("ajout d'un nouveau bureau du vote"));
  gtk_widget_show (label3MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label3MM, 256, 8);
  gtk_widget_set_size_request (label3MM, 256, 24);

  label5MM = gtk_label_new (_("adresse"));
  gtk_widget_show (label5MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label5MM, 24, 104);
  gtk_widget_set_size_request (label5MM, 88, 16);

  label7MM = gtk_label_new (_("capacite election"));
  gtk_widget_show (label7MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label7MM, 24, 144);
  gtk_widget_set_size_request (label7MM, 128, 32);

  label8MM = gtk_label_new (_("capacite observateur "));
  gtk_widget_show (label8MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label8MM, 16, 200);
  gtk_widget_set_size_request (label8MM, 168, 24);

  label9MM = gtk_label_new (_("nombre des salles"));
  gtk_widget_show (label9MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label9MM, 24, 264);
  gtk_widget_set_size_request (label9MM, 120, 16);

  label10MM = gtk_label_new (_("etat des salles "));
  gtk_widget_show (label10MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label10MM, 24, 328);
  gtk_widget_set_size_request (label10MM, 128, 16);

  label11MM = gtk_label_new (_("ID agent "));
  gtk_widget_show (label11MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label11MM, 48, 368);
  gtk_widget_set_size_request (label11MM, 72, 16);

  label4MM = gtk_label_new (_("identifiant "));
  gtk_widget_show (label4MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label4MM, 32, 56);
  gtk_widget_set_size_request (label4MM, 96, 16);

  checkbutton1MM = gtk_check_button_new_with_mnemonic (_("10"));
  gtk_widget_show (checkbutton1MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), checkbutton1MM, 216, 200);
  gtk_widget_set_size_request (checkbutton1MM, 118, 24);

  checkbutton2MM = gtk_check_button_new_with_mnemonic (_("20"));
  gtk_widget_show (checkbutton2MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), checkbutton2MM, 352, 200);
  gtk_widget_set_size_request (checkbutton2MM, 118, 24);

  checkbutton3MM = gtk_check_button_new_with_mnemonic (_("30"));
  gtk_widget_show (checkbutton3MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), checkbutton3MM, 504, 200);
  gtk_widget_set_size_request (checkbutton3MM, 118, 24);

  radiobutton1MM = gtk_radio_button_new_with_mnemonic (NULL, _("disponible "));
  gtk_widget_show (radiobutton1MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), radiobutton1MM, 200, 320);
  gtk_widget_set_size_request (radiobutton1MM, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1MM), radiobutton1MM_group);
  radiobutton1MM_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1MM));

  radiobutton2MM = gtk_radio_button_new_with_mnemonic (NULL, _("non disponible "));
  gtk_widget_show (radiobutton2MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), radiobutton2MM, 360, 320);
  gtk_widget_set_size_request (radiobutton2MM, 144, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2MM), radiobutton1MM_group);
  radiobutton1MM_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2MM));

  combobox4MM = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), combobox4MM, 192, 360);
  gtk_widget_set_size_request (combobox4MM, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4MM), _("1234456AG"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4MM), _("3458351AG"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4MM), _("9804326AG"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4MM), _("2265410AG"));

  button6MM = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (button6MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), button6MM, 56, 448);
  gtk_widget_set_size_request (button6MM, 104, 24);

  button5MM = gtk_button_new_with_mnemonic (_("confirmer "));
  gtk_widget_show (button5MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), button5MM, 616, 440);
  gtk_widget_set_size_request (button5MM, 112, 32);

  g_signal_connect ((gpointer) checkbutton1MM, "toggled",
                    G_CALLBACK (on_checkbutton1MM_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2MM, "toggled",
                    G_CALLBACK (on_checkbutton2MM_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton3MM, "toggled",
                    G_CALLBACK (on_checkbutton3MM_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1MM, "toggled",
                    G_CALLBACK (on_radiobutton1MM_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2MM, "toggled",
                    G_CALLBACK (on_radiobutton2MM_toggled),
                    NULL);
  g_signal_connect ((gpointer) button6MM, "clicked",
                    G_CALLBACK (on_button6MM_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5MM, "clicked",
                    G_CALLBACK (on_button5MM_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mariem2, mariem2, "mariem2");
  GLADE_HOOKUP_OBJECT (mariem2, fixed2MM, "fixed2MM");
  GLADE_HOOKUP_OBJECT (mariem2, entry1MM, "entry1MM");
  GLADE_HOOKUP_OBJECT (mariem2, entry2MM, "entry2MM");
  GLADE_HOOKUP_OBJECT (mariem2, label6, "label6");
  GLADE_HOOKUP_OBJECT (mariem2, spinbutton1MM, "spinbutton1MM");
  GLADE_HOOKUP_OBJECT (mariem2, entry3MM, "entry3MM");
  GLADE_HOOKUP_OBJECT (mariem2, label3MM, "label3MM");
  GLADE_HOOKUP_OBJECT (mariem2, label5MM, "label5MM");
  GLADE_HOOKUP_OBJECT (mariem2, label7MM, "label7MM");
  GLADE_HOOKUP_OBJECT (mariem2, label8MM, "label8MM");
  GLADE_HOOKUP_OBJECT (mariem2, label9MM, "label9MM");
  GLADE_HOOKUP_OBJECT (mariem2, label10MM, "label10MM");
  GLADE_HOOKUP_OBJECT (mariem2, label11MM, "label11MM");
  GLADE_HOOKUP_OBJECT (mariem2, label4MM, "label4MM");
  GLADE_HOOKUP_OBJECT (mariem2, checkbutton1MM, "checkbutton1MM");
  GLADE_HOOKUP_OBJECT (mariem2, checkbutton2MM, "checkbutton2MM");
  GLADE_HOOKUP_OBJECT (mariem2, checkbutton3MM, "checkbutton3MM");
  GLADE_HOOKUP_OBJECT (mariem2, radiobutton1MM, "radiobutton1MM");
  GLADE_HOOKUP_OBJECT (mariem2, radiobutton2MM, "radiobutton2MM");
  GLADE_HOOKUP_OBJECT (mariem2, combobox4MM, "combobox4MM");
  GLADE_HOOKUP_OBJECT (mariem2, button6MM, "button6MM");
  GLADE_HOOKUP_OBJECT (mariem2, button5MM, "button5MM");

  return mariem2;
}

GtkWidget*
create_mariem3 (void)
{
  GtkWidget *mariem3;
  GtkWidget *fixed3MM;
  GtkWidget *fixed4MM;
  GtkWidget *entry4MM;
  GtkWidget *entry5MM;
  GtkWidget *label12;
  GtkObject *spinbutton2MM_adj;
  GtkWidget *spinbutton2MM;
  GtkWidget *entry6MM;
  GtkWidget *label19MM;
  GtkWidget *label20MM;
  GtkWidget *label16MM;
  GtkWidget *label15MM;
  GtkWidget *label17MM;
  GtkWidget *label18MM;
  GtkWidget *label13MM;
  GtkWidget *label23MM;
  GtkWidget *button9MM;
  GtkWidget *checkbutton6MM;
  GtkWidget *checkbutton5MM;
  GtkWidget *checkbutton4MM;
  GtkWidget *button7MM;
  GtkWidget *radiobutton1MM;
  GSList *radiobutton1MM_group = NULL;
  GtkWidget *combobox3MM;
  GtkWidget *button8MM;
  GtkWidget *radiobutton3MM;

  mariem3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mariem3), _("modification bureau du vote"));

  fixed3MM = gtk_fixed_new ();
  gtk_widget_show (fixed3MM);
  gtk_container_add (GTK_CONTAINER (mariem3), fixed3MM);

  fixed4MM = gtk_fixed_new ();
  gtk_widget_show (fixed4MM);
  gtk_fixed_put (GTK_FIXED (fixed3MM), fixed4MM, 16, 8);
  gtk_widget_set_size_request (fixed4MM, 0, 0);

  entry4MM = gtk_entry_new ();
  gtk_widget_show (entry4MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), entry4MM, 192, 56);
  gtk_widget_set_size_request (entry4MM, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4MM), 8226);

  entry5MM = gtk_entry_new ();
  gtk_widget_show (entry5MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), entry5MM, 192, 96);
  gtk_widget_set_size_request (entry5MM, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5MM), 8226);

  label12 = gtk_label_new ("");
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label12, 24, 144);
  gtk_widget_set_size_request (label12, 41, 17);

  spinbutton2MM_adj = gtk_adjustment_new (1, 1, 5, 1, 10, 10);
  spinbutton2MM = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2MM_adj), 1, 0);
  gtk_widget_show (spinbutton2MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), spinbutton2MM, 200, 256);
  gtk_widget_set_size_request (spinbutton2MM, 60, 27);

  entry6MM = gtk_entry_new ();
  gtk_widget_show (entry6MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), entry6MM, 192, 144);
  gtk_widget_set_size_request (entry6MM, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6MM), 8226);

  label19MM = gtk_label_new (_("modification d'un bureau du vote"));
  gtk_widget_show (label19MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label19MM, 256, 8);
  gtk_widget_set_size_request (label19MM, 256, 24);

  label20MM = gtk_label_new (_("identifiant "));
  gtk_widget_show (label20MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label20MM, 32, 56);
  gtk_widget_set_size_request (label20MM, 96, 16);

  label16MM = gtk_label_new (_("capacite observateur "));
  gtk_widget_show (label16MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label16MM, 16, 200);
  gtk_widget_set_size_request (label16MM, 168, 24);

  label15MM = gtk_label_new (_("nombre des salles"));
  gtk_widget_show (label15MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label15MM, 24, 264);
  gtk_widget_set_size_request (label15MM, 120, 16);

  label17MM = gtk_label_new (_("etat des salles "));
  gtk_widget_show (label17MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label17MM, 24, 320);
  gtk_widget_set_size_request (label17MM, 128, 16);

  label18MM = gtk_label_new (_("ID agent "));
  gtk_widget_show (label18MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label18MM, 48, 376);
  gtk_widget_set_size_request (label18MM, 72, 16);

  label13MM = gtk_label_new (_("adresse"));
  gtk_widget_show (label13MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label13MM, 24, 104);
  gtk_widget_set_size_request (label13MM, 88, 16);

  label23MM = gtk_label_new (_("capacite election"));
  gtk_widget_show (label23MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label23MM, 24, 152);
  gtk_widget_set_size_request (label23MM, 136, 16);

  button9MM = gtk_button_new_with_mnemonic (_("rechercher "));
  gtk_widget_show (button9MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), button9MM, 424, 56);
  gtk_widget_set_size_request (button9MM, 96, 24);

  checkbutton6MM = gtk_check_button_new_with_mnemonic (_("10"));
  gtk_widget_show (checkbutton6MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), checkbutton6MM, 216, 200);
  gtk_widget_set_size_request (checkbutton6MM, 118, 24);

  checkbutton5MM = gtk_check_button_new_with_mnemonic (_("20"));
  gtk_widget_show (checkbutton5MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), checkbutton5MM, 352, 200);
  gtk_widget_set_size_request (checkbutton5MM, 118, 24);

  checkbutton4MM = gtk_check_button_new_with_mnemonic (_("30"));
  gtk_widget_show (checkbutton4MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), checkbutton4MM, 504, 200);
  gtk_widget_set_size_request (checkbutton4MM, 118, 24);

  button7MM = gtk_button_new_with_mnemonic (_("confirmer "));
  gtk_widget_show (button7MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), button7MM, 664, 472);
  gtk_widget_set_size_request (button7MM, 120, 24);

  radiobutton1MM = gtk_radio_button_new_with_mnemonic (NULL, _("non disponible "));
  gtk_widget_show (radiobutton1MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), radiobutton1MM, 360, 320);
  gtk_widget_set_size_request (radiobutton1MM, 136, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1MM), radiobutton1MM_group);
  radiobutton1MM_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1MM));

  combobox3MM = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), combobox3MM, 176, 368);
  gtk_widget_set_size_request (combobox3MM, 200, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3MM), _("1234456AG"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3MM), _("3458351AG"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3MM), _("9804326AG"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3MM), _("2265410AG"));

  button8MM = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (button8MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), button8MM, 32, 464);
  gtk_widget_set_size_request (button8MM, 104, 24);

  radiobutton3MM = gtk_radio_button_new_with_mnemonic (NULL, _("disponible "));
  gtk_widget_show (radiobutton3MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), radiobutton3MM, 200, 320);
  gtk_widget_set_size_request (radiobutton3MM, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3MM), radiobutton1MM_group);
  radiobutton1MM_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3MM));

  g_signal_connect ((gpointer) button9MM, "clicked",
                    G_CALLBACK (on_button9MM_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton6MM, "toggled",
                    G_CALLBACK (on_checkbutton6MM_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton5MM, "toggled",
                    G_CALLBACK (on_checkbutton5MM_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton4MM, "toggled",
                    G_CALLBACK (on_checkbutton4MM_toggled),
                    NULL);
  g_signal_connect ((gpointer) button7MM, "clicked",
                    G_CALLBACK (on_button7MM_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1MM, "toggled",
                    G_CALLBACK (on_radiobutton1MM_toggled),
                    NULL);
  g_signal_connect ((gpointer) button8MM, "clicked",
                    G_CALLBACK (on_button8MM_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3MM, "toggled",
                    G_CALLBACK (on_radiobutton3MM_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mariem3, mariem3, "mariem3");
  GLADE_HOOKUP_OBJECT (mariem3, fixed3MM, "fixed3MM");
  GLADE_HOOKUP_OBJECT (mariem3, fixed4MM, "fixed4MM");
  GLADE_HOOKUP_OBJECT (mariem3, entry4MM, "entry4MM");
  GLADE_HOOKUP_OBJECT (mariem3, entry5MM, "entry5MM");
  GLADE_HOOKUP_OBJECT (mariem3, label12, "label12");
  GLADE_HOOKUP_OBJECT (mariem3, spinbutton2MM, "spinbutton2MM");
  GLADE_HOOKUP_OBJECT (mariem3, entry6MM, "entry6MM");
  GLADE_HOOKUP_OBJECT (mariem3, label19MM, "label19MM");
  GLADE_HOOKUP_OBJECT (mariem3, label20MM, "label20MM");
  GLADE_HOOKUP_OBJECT (mariem3, label16MM, "label16MM");
  GLADE_HOOKUP_OBJECT (mariem3, label15MM, "label15MM");
  GLADE_HOOKUP_OBJECT (mariem3, label17MM, "label17MM");
  GLADE_HOOKUP_OBJECT (mariem3, label18MM, "label18MM");
  GLADE_HOOKUP_OBJECT (mariem3, label13MM, "label13MM");
  GLADE_HOOKUP_OBJECT (mariem3, label23MM, "label23MM");
  GLADE_HOOKUP_OBJECT (mariem3, button9MM, "button9MM");
  GLADE_HOOKUP_OBJECT (mariem3, checkbutton6MM, "checkbutton6MM");
  GLADE_HOOKUP_OBJECT (mariem3, checkbutton5MM, "checkbutton5MM");
  GLADE_HOOKUP_OBJECT (mariem3, checkbutton4MM, "checkbutton4MM");
  GLADE_HOOKUP_OBJECT (mariem3, button7MM, "button7MM");
  GLADE_HOOKUP_OBJECT (mariem3, radiobutton1MM, "radiobutton1MM");
  GLADE_HOOKUP_OBJECT (mariem3, combobox3MM, "combobox3MM");
  GLADE_HOOKUP_OBJECT (mariem3, button8MM, "button8MM");
  GLADE_HOOKUP_OBJECT (mariem3, radiobutton3MM, "radiobutton3MM");

  return mariem3;
}

GtkWidget*
create_mariem_4 (void)
{
  GtkWidget *mariem_4;
  GtkWidget *fixed5MM;
  GtkWidget *entry8MM;
  GtkWidget *label21MM;
  GtkWidget *button11MM;
  GtkWidget *button10MM;
  GtkWidget *label22MM;

  mariem_4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mariem_4), _("suppression bureau du vote"));

  fixed5MM = gtk_fixed_new ();
  gtk_widget_show (fixed5MM);
  gtk_container_add (GTK_CONTAINER (mariem_4), fixed5MM);

  entry8MM = gtk_entry_new ();
  gtk_widget_show (entry8MM);
  gtk_fixed_put (GTK_FIXED (fixed5MM), entry8MM, 192, 96);
  gtk_widget_set_size_request (entry8MM, 232, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8MM), 8226);

  label21MM = gtk_label_new (_("suppression  d'un bureau du vote "));
  gtk_widget_show (label21MM);
  gtk_fixed_put (GTK_FIXED (fixed5MM), label21MM, 200, 16);
  gtk_widget_set_size_request (label21MM, 232, 24);

  button11MM = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (button11MM);
  gtk_fixed_put (GTK_FIXED (fixed5MM), button11MM, 24, 264);
  gtk_widget_set_size_request (button11MM, 74, 29);

  button10MM = gtk_button_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (button10MM);
  gtk_fixed_put (GTK_FIXED (fixed5MM), button10MM, 424, 136);
  gtk_widget_set_size_request (button10MM, 96, 24);

  label22MM = gtk_label_new (_("identifiant "));
  gtk_widget_show (label22MM);
  gtk_fixed_put (GTK_FIXED (fixed5MM), label22MM, 80, 104);
  gtk_widget_set_size_request (label22MM, 104, 16);

  g_signal_connect ((gpointer) button11MM, "clicked",
                    G_CALLBACK (on_button11MM_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10MM, "clicked",
                    G_CALLBACK (on_button10MM_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mariem_4, mariem_4, "mariem_4");
  GLADE_HOOKUP_OBJECT (mariem_4, fixed5MM, "fixed5MM");
  GLADE_HOOKUP_OBJECT (mariem_4, entry8MM, "entry8MM");
  GLADE_HOOKUP_OBJECT (mariem_4, label21MM, "label21MM");
  GLADE_HOOKUP_OBJECT (mariem_4, button11MM, "button11MM");
  GLADE_HOOKUP_OBJECT (mariem_4, button10MM, "button10MM");
  GLADE_HOOKUP_OBJECT (mariem_4, label22MM, "label22MM");

  return mariem_4;
}

