/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *mariem_1;
  GtkWidget *mariem2;
  GtkWidget *mariem3;
  GtkWidget *mariem_4;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  mariem_1 = create_mariem_1 ();
  gtk_widget_show (mariem_1);
 /* mariem2 = create_mariem2 ();
  gtk_widget_show (mariem2);
  mariem3 = create_mariem3 ();
  gtk_widget_show (mariem3);
  mariem_4 = create_mariem_4 ();
  gtk_widget_show (mariem_4);*/

  gtk_main ();
  return 0;
}

