/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1_fatma (void)
{
  GtkWidget *window1_fatma;
  GtkWidget *alignment1;
  GtkWidget *fixed1;
  GtkWidget *label_election_fatma;
  GtkWidget *ajout_fatma;
  GtkWidget *modifier_fatma;
  GtkWidget *supprimer_fatma;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview_fatma;

  window1_fatma = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1_fatma), _("Affichage"));

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (window1_fatma), alignment1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (alignment1), fixed1);

  label_election_fatma = gtk_label_new (_("Election municipale"));
  gtk_widget_show (label_election_fatma);
  gtk_fixed_put (GTK_FIXED (fixed1), label_election_fatma, 232, 48);
  gtk_widget_set_size_request (label_election_fatma, 193, 56);
  gtk_label_set_justify (GTK_LABEL (label_election_fatma), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label_election_fatma), 0.5, 0.41);

  ajout_fatma = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (ajout_fatma);
  gtk_fixed_put (GTK_FIXED (fixed1), ajout_fatma, 88, 416);
  gtk_widget_set_size_request (ajout_fatma, 136, 32);

  modifier_fatma = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (modifier_fatma);
  gtk_fixed_put (GTK_FIXED (fixed1), modifier_fatma, 272, 416);
  gtk_widget_set_size_request (modifier_fatma, 136, 32);

  supprimer_fatma = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (supprimer_fatma);
  gtk_fixed_put (GTK_FIXED (fixed1), supprimer_fatma, 456, 416);
  gtk_widget_set_size_request (supprimer_fatma, 136, 32);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed1), scrolledwindow2, 128, 136);
  gtk_widget_set_size_request (scrolledwindow2, 444, 224);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  treeview_fatma = gtk_tree_view_new ();
  gtk_widget_show (treeview_fatma);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview_fatma);
  gtk_widget_set_size_request (treeview_fatma, 444, 224);
  gtk_container_set_border_width (GTK_CONTAINER (treeview_fatma), 50);
  gtk_tree_view_set_hover_selection (GTK_TREE_VIEW (treeview_fatma), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1_fatma, window1_fatma, "window1_fatma");
  GLADE_HOOKUP_OBJECT (window1_fatma, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1_fatma, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1_fatma, label_election_fatma, "label_election_fatma");
  GLADE_HOOKUP_OBJECT (window1_fatma, ajout_fatma, "ajout_fatma");
  GLADE_HOOKUP_OBJECT (window1_fatma, modifier_fatma, "modifier_fatma");
  GLADE_HOOKUP_OBJECT (window1_fatma, supprimer_fatma, "supprimer_fatma");
  GLADE_HOOKUP_OBJECT (window1_fatma, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (window1_fatma, treeview_fatma, "treeview_fatma");

  return window1_fatma;
}

GtkWidget*
create_window2_fatma (void)
{
  GtkWidget *window2_fatma;
  GtkWidget *fixed2;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkWidget *indentifiant_fatma;
  GtkWidget *label8;
  GtkWidget *label2;
  GtkWidget *jour_fatma;
  GtkWidget *mois_fatma;
  GtkWidget *annee_fatma;
  GtkWidget *label1;
  GtkWidget *entry5;
  GtkWidget *button12;
  GtkWidget *confirmer_fatma;
  GtkWidget *annuler2_fatma;
  GtkWidget *label19;
  GtkWidget *comboboxentry5;
  GtkWidget *checkbutton3;
  GtkWidget *label17;
  GtkWidget *checkbutton4;
  GtkWidget *label7;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton3;
  GtkWidget *radiobutton4;
  GtkWidget *radiobutton5;
  GtkWidget *radiobutton6;
  GtkWidget *entry7;

  window2_fatma = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2_fatma), _("Modifier"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2_fatma), fixed2);

  spinbutton5_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton5, 232, 256);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton6, 384, 256);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  spinbutton7_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton7, 520, 256);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  indentifiant_fatma = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (indentifiant_fatma);
  gtk_fixed_put (GTK_FIXED (fixed2), indentifiant_fatma, 72, 160);
  gtk_widget_set_size_request (indentifiant_fatma, 80, 24);

  label8 = gtk_label_new (_("Municipalit\303\251 :"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 40, 328);
  gtk_widget_set_size_request (label8, 153, 24);

  label2 = gtk_label_new (_("Date:"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 64, 256);
  gtk_widget_set_size_request (label2, 64, 24);

  jour_fatma = gtk_label_new (_("jour"));
  gtk_widget_show (jour_fatma);
  gtk_fixed_put (GTK_FIXED (fixed2), jour_fatma, 176, 256);
  gtk_widget_set_size_request (jour_fatma, 49, 24);

  mois_fatma = gtk_label_new (_("mois"));
  gtk_widget_show (mois_fatma);
  gtk_fixed_put (GTK_FIXED (fixed2), mois_fatma, 320, 256);
  gtk_widget_set_size_request (mois_fatma, 49, 24);

  annee_fatma = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (annee_fatma);
  gtk_fixed_put (GTK_FIXED (fixed2), annee_fatma, 456, 256);
  gtk_widget_set_size_request (annee_fatma, 60, 27);

  label1 = gtk_label_new (_("modifier"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed2), label1, 224, 48);
  gtk_widget_set_size_request (label1, 152, 48);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_CENTER);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed2), entry5, 192, 160);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  button12 = gtk_button_new_with_mnemonic (_("chercher"));
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed2), button12, 384, 160);
  gtk_widget_set_size_request (button12, 136, 32);

  confirmer_fatma = gtk_button_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (confirmer_fatma);
  gtk_fixed_put (GTK_FIXED (fixed2), confirmer_fatma, 96, 752);
  gtk_widget_set_size_request (confirmer_fatma, 136, 32);

  annuler2_fatma = gtk_button_new_with_mnemonic (_("annuler"));
  gtk_widget_show (annuler2_fatma);
  gtk_fixed_put (GTK_FIXED (fixed2), annuler2_fatma, 360, 752);
  gtk_widget_set_size_request (annuler2_fatma, 136, 32);

  label19 = gtk_label_new (_("Nombre de conseillers :"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed2), label19, 64, 568);
  gtk_widget_set_size_request (label19, 152, 24);
  gtk_label_set_justify (GTK_LABEL (label19), GTK_JUSTIFY_CENTER);

  comboboxentry5 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry5);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxentry5, 240, 568);
  gtk_widget_set_size_request (comboboxentry5, 189, 29);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("achev\303\251e"));
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton3, 216, 640);
  gtk_widget_set_size_request (checkbutton3, 118, 24);

  label17 = gtk_label_new (_("Satut des \303\251lections :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed2), label17, 64, 640);
  gtk_widget_set_size_request (label17, 128, 17);

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("en cours"));
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton4, 368, 640);
  gtk_widget_set_size_request (checkbutton4, 118, 24);

  label7 = gtk_label_new (_("Nombre d'habitant :"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 64, 384);
  gtk_widget_set_size_request (label7, 144, 24);
  gtk_label_set_justify (GTK_LABEL (label7), GTK_JUSTIFY_CENTER);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("jusqu'\303\240 5000"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton1, 232, 384);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("5001-10000"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton2, 232, 440);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("25001-50000"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton3, 232, 496);
  gtk_widget_set_size_request (radiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("50001-100000"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton4, 424, 384);
  gtk_widget_set_size_request (radiobutton4, 140, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("100000-500000"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton5, 424, 440);
  gtk_widget_set_size_request (radiobutton5, 150, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("plus de 500000"));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton6, 424, 496);
  gtk_widget_set_size_request (radiobutton6, 150, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed2), entry7, 232, 328);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2_fatma, window2_fatma, "window2_fatma");
  GLADE_HOOKUP_OBJECT (window2_fatma, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2_fatma, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (window2_fatma, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (window2_fatma, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (window2_fatma, indentifiant_fatma, "indentifiant_fatma");
  GLADE_HOOKUP_OBJECT (window2_fatma, label8, "label8");
  GLADE_HOOKUP_OBJECT (window2_fatma, label2, "label2");
  GLADE_HOOKUP_OBJECT (window2_fatma, jour_fatma, "jour_fatma");
  GLADE_HOOKUP_OBJECT (window2_fatma, mois_fatma, "mois_fatma");
  GLADE_HOOKUP_OBJECT (window2_fatma, annee_fatma, "annee_fatma");
  GLADE_HOOKUP_OBJECT (window2_fatma, label1, "label1");
  GLADE_HOOKUP_OBJECT (window2_fatma, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window2_fatma, button12, "button12");
  GLADE_HOOKUP_OBJECT (window2_fatma, confirmer_fatma, "confirmer_fatma");
  GLADE_HOOKUP_OBJECT (window2_fatma, annuler2_fatma, "annuler2_fatma");
  GLADE_HOOKUP_OBJECT (window2_fatma, label19, "label19");
  GLADE_HOOKUP_OBJECT (window2_fatma, comboboxentry5, "comboboxentry5");
  GLADE_HOOKUP_OBJECT (window2_fatma, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (window2_fatma, label17, "label17");
  GLADE_HOOKUP_OBJECT (window2_fatma, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (window2_fatma, label7, "label7");
  GLADE_HOOKUP_OBJECT (window2_fatma, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (window2_fatma, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (window2_fatma, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (window2_fatma, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (window2_fatma, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (window2_fatma, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (window2_fatma, entry7, "entry7");

  return window2_fatma;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed3;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkObject *spinbutton10_adj;
  GtkWidget *spinbutton10;
  GtkWidget *entry2;
  GtkWidget *label16;
  GtkWidget *label12;
  GtkWidget *button10;
  GtkWidget *button11;
  GtkWidget *label18;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *label15;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label20;
  GtkWidget *comboboxentry4;
  GtkWidget *label14;
  GtkWidget *entry6;
  GtkWidget *radiobutton7;
  GSList *radiobutton7_group = NULL;
  GtkWidget *label13;
  GtkWidget *radiobutton8;
  GSList *radiobutton8_group = NULL;
  GtkWidget *radiobutton9;
  GSList *radiobutton9_group = NULL;
  GtkWidget *radiobutton10;
  GSList *radiobutton10_group = NULL;
  GtkWidget *radiobutton11;
  GSList *radiobutton11_group = NULL;
  GtkWidget *radiobutton12;
  GSList *radiobutton12_group = NULL;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("ajouter"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window2), fixed3);

  spinbutton8_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton8, 344, 512);
  gtk_widget_set_size_request (spinbutton8, 60, 27);

  spinbutton9_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_show (spinbutton9);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton9, 200, 512);
  gtk_widget_set_size_request (spinbutton9, 60, 27);

  spinbutton10_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10_adj), 1, 0);
  gtk_widget_show (spinbutton10);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton10, 496, 512);
  gtk_widget_set_size_request (spinbutton10, 60, 27);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry2, 264, 88);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label16 = gtk_label_new (_("Ajout"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 256, 8);
  gtk_widget_set_size_request (label16, 152, 48);
  gtk_label_set_justify (GTK_LABEL (label16), GTK_JUSTIFY_CENTER);

  label12 = gtk_label_new (_("identifiant :"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 88, 88);
  gtk_widget_set_size_request (label12, 80, 24);

  button10 = gtk_button_new_with_mnemonic (_("annuler"));
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed3), button10, 368, 688);
  gtk_widget_set_size_request (button10, 136, 32);

  button11 = gtk_button_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed3), button11, 120, 688);
  gtk_widget_set_size_request (button11, 136, 32);

  label18 = gtk_label_new (_("Satut des \303\251lections :"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 64, 608);
  gtk_widget_set_size_request (label18, 128, 17);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("achev\303\251e"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton1, 216, 600);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("en cours"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton2, 360, 600);
  gtk_widget_set_size_request (checkbutton2, 118, 24);

  label15 = gtk_label_new (_("date:"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 64, 512);
  gtk_widget_set_size_request (label15, 64, 24);

  label9 = gtk_label_new (_("jour"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 144, 512);
  gtk_widget_set_size_request (label9, 56, 24);

  label10 = gtk_label_new (_("mois"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 272, 512);
  gtk_widget_set_size_request (label10, 49, 24);

  label11 = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 424, 512);
  gtk_widget_set_size_request (label11, 60, 27);

  label20 = gtk_label_new (_("Nombre de conseillers:"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 72, 448);
  gtk_widget_set_size_request (label20, 152, 16);

  comboboxentry4 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry4);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentry4, 264, 440);
  gtk_widget_set_size_request (comboboxentry4, 189, 29);

  label14 = gtk_label_new (_("Municipalit\303\251 :"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 56, 152);
  gtk_widget_set_size_request (label14, 153, 24);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6, 264, 152);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("jusqu'\303\240 5000"));
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton7, 248, 224);
  gtk_widget_set_size_request (radiobutton7, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  label13 = gtk_label_new (_("nombre d'habitant :"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 72, 224);
  gtk_widget_set_size_request (label13, 144, 24);
  gtk_label_set_justify (GTK_LABEL (label13), GTK_JUSTIFY_CENTER);

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, _("5001-10000"));
  gtk_widget_show (radiobutton8);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton8, 248, 296);
  gtk_widget_set_size_request (radiobutton8, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton8_group);
  radiobutton8_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  radiobutton9 = gtk_radio_button_new_with_mnemonic (NULL, _("25001-50000"));
  gtk_widget_show (radiobutton9);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton9, 248, 368);
  gtk_widget_set_size_request (radiobutton9, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton9), radiobutton9_group);
  radiobutton9_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton9));

  radiobutton10 = gtk_radio_button_new_with_mnemonic (NULL, _("50001-100000"));
  gtk_widget_show (radiobutton10);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton10, 400, 224);
  gtk_widget_set_size_request (radiobutton10, 140, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton10), radiobutton10_group);
  radiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton10));

  radiobutton11 = gtk_radio_button_new_with_mnemonic (NULL, _("100000-500000"));
  gtk_widget_show (radiobutton11);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton11, 400, 296);
  gtk_widget_set_size_request (radiobutton11, 150, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11), radiobutton11_group);
  radiobutton11_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11));

  radiobutton12 = gtk_radio_button_new_with_mnemonic (NULL, _("plus de 500000"));
  gtk_widget_show (radiobutton12);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton12, 400, 368);
  gtk_widget_set_size_request (radiobutton12, 150, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton12), radiobutton12_group);
  radiobutton12_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton12));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window2, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (window2, spinbutton9, "spinbutton9");
  GLADE_HOOKUP_OBJECT (window2, spinbutton10, "spinbutton10");
  GLADE_HOOKUP_OBJECT (window2, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window2, label16, "label16");
  GLADE_HOOKUP_OBJECT (window2, label12, "label12");
  GLADE_HOOKUP_OBJECT (window2, button10, "button10");
  GLADE_HOOKUP_OBJECT (window2, button11, "button11");
  GLADE_HOOKUP_OBJECT (window2, label18, "label18");
  GLADE_HOOKUP_OBJECT (window2, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (window2, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (window2, label15, "label15");
  GLADE_HOOKUP_OBJECT (window2, label9, "label9");
  GLADE_HOOKUP_OBJECT (window2, label10, "label10");
  GLADE_HOOKUP_OBJECT (window2, label11, "label11");
  GLADE_HOOKUP_OBJECT (window2, label20, "label20");
  GLADE_HOOKUP_OBJECT (window2, comboboxentry4, "comboboxentry4");
  GLADE_HOOKUP_OBJECT (window2, label14, "label14");
  GLADE_HOOKUP_OBJECT (window2, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window2, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (window2, label13, "label13");
  GLADE_HOOKUP_OBJECT (window2, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (window2, radiobutton9, "radiobutton9");
  GLADE_HOOKUP_OBJECT (window2, radiobutton10, "radiobutton10");
  GLADE_HOOKUP_OBJECT (window2, radiobutton11, "radiobutton11");
  GLADE_HOOKUP_OBJECT (window2, radiobutton12, "radiobutton12");

  return window2;
}

