/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Ajouter_fatma (void);
GtkWidget* create_Modifier_fatma (void);
GtkWidget* create_afficher_fatma (void);
GtkWidget* create_supprimer_fatma (void);
