/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Ajouter_fatma;
  GtkWidget *Modifier_fatma;
  GtkWidget *afficher_fatma;
  GtkWidget *supprimer_fatma;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
 /* Ajouter_fatma = create_Ajouter_fatma ();
  gtk_widget_show (Ajouter_fatma);
  Modifier_fatma = create_Modifier_fatma ();
  gtk_widget_show (Modifier_fatma);*/
  afficher_fatma = create_afficher_fatma ();
  gtk_widget_show (afficher_fatma);
 /* supprimer_fatma = create_supprimer_fatma ();
  gtk_widget_show (supprimer_fatma);*/

  gtk_main ();
  return 0;
}

