/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_GDU1 (void)
{
  GtkWidget *GDU1;
  GtkWidget *FX1;
  GtkWidget *trvf1;
  GtkWidget *boutonretour;
  GtkWidget *boutonsuppr;
  GtkWidget *boutonajouter;
  GtkWidget *boutonmodifier;
  GtkWidget *titlelabel1;
  GtkWidget *titlelabel2;

  GDU1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GDU1), _("Gestion Des Utilisateurs"));

  FX1 = gtk_fixed_new ();
  gtk_widget_show (FX1);
  gtk_container_add (GTK_CONTAINER (GDU1), FX1);

  trvf1 = gtk_tree_view_new ();
  gtk_widget_show (trvf1);
  gtk_fixed_put (GTK_FIXED (FX1), trvf1, 128, 136);
  gtk_widget_set_size_request (trvf1, 760, 224);

  boutonretour = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (boutonretour);
  gtk_fixed_put (GTK_FIXED (FX1), boutonretour, 48, 456);
  gtk_widget_set_size_request (boutonretour, 104, 40);

  boutonsuppr = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (boutonsuppr);
  gtk_fixed_put (GTK_FIXED (FX1), boutonsuppr, 624, 376);
  gtk_widget_set_size_request (boutonsuppr, 104, 40);

  boutonajouter = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (boutonajouter);
  gtk_fixed_put (GTK_FIXED (FX1), boutonajouter, 272, 376);
  gtk_widget_set_size_request (boutonajouter, 104, 40);

  boutonmodifier = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (boutonmodifier);
  gtk_fixed_put (GTK_FIXED (FX1), boutonmodifier, 448, 376);
  gtk_widget_set_size_request (boutonmodifier, 104, 40);

  titlelabel1 = gtk_label_new (_("Gestion Des Utilisateurs"));
  gtk_widget_show (titlelabel1);
  gtk_fixed_put (GTK_FIXED (FX1), titlelabel1, 400, 64);
  gtk_widget_set_size_request (titlelabel1, 192, 16);

  titlelabel2 = gtk_label_new (_("Liste des Utilisateurs"));
  gtk_widget_show (titlelabel2);
  gtk_fixed_put (GTK_FIXED (FX1), titlelabel2, 400, 96);
  gtk_widget_set_size_request (titlelabel2, 192, 16);

  g_signal_connect ((gpointer) boutonsuppr, "clicked",
                    G_CALLBACK (on_boutonsuppr_clicked),
                    NULL);
  g_signal_connect ((gpointer) boutonajouter, "clicked",
                    G_CALLBACK (on_boutonajouter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GDU1, GDU1, "GDU1");
  GLADE_HOOKUP_OBJECT (GDU1, FX1, "FX1");
  GLADE_HOOKUP_OBJECT (GDU1, trvf1, "trvf1");
  GLADE_HOOKUP_OBJECT (GDU1, boutonretour, "boutonretour");
  GLADE_HOOKUP_OBJECT (GDU1, boutonsuppr, "boutonsuppr");
  GLADE_HOOKUP_OBJECT (GDU1, boutonajouter, "boutonajouter");
  GLADE_HOOKUP_OBJECT (GDU1, boutonmodifier, "boutonmodifier");
  GLADE_HOOKUP_OBJECT (GDU1, titlelabel1, "titlelabel1");
  GLADE_HOOKUP_OBJECT (GDU1, titlelabel2, "titlelabel2");

  return GDU1;
}

GtkWidget*
create_GDU2 (void)
{
  GtkWidget *GDU2;
  GtkWidget *FX2;
  GtkWidget *titlelabel3;
  GtkWidget *txtentrynom;
  GtkWidget *txtentryprenom;
  GtkWidget *labelnom;
  GtkWidget *labelprenom;
  GtkObject *spinbuttonj_adj;
  GtkWidget *spinbuttonj;
  GtkObject *spinbuttonm_adj;
  GtkWidget *spinbuttonm;
  GtkWidget *txtentrycin;
  GtkWidget *txtentryid;
  GtkWidget *labelid;
  GtkWidget *txtentrypass;
  GtkWidget *labelcin;
  GtkWidget *labelpass;
  GtkWidget *labelvote;
  GtkWidget *txtentrybv;
  GtkWidget *labelbv;
  GtkWidget *labeltp;
  GtkWidget *labeldn;
  GtkWidget *labelgender;
  GtkWidget *labeltitleaj;
  GtkWidget *comboboxannee;
  GtkWidget *comboboxtypeuts;
  GtkWidget *radiobuttonf;
  GSList *radiobuttonf_group = NULL;
  GtkWidget *radiobuttonm;
  GtkWidget *checkbtn;
  GtkWidget *boutonconfirmeraj;
  GtkWidget *boutonrtraj;
  GtkWidget *casevote;
  GtkWidget *checkbtnlabel;

  GDU2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GDU2), _("Gestion Des Utilisateurs"));

  FX2 = gtk_fixed_new ();
  gtk_widget_show (FX2);
  gtk_container_add (GTK_CONTAINER (GDU2), FX2);

  titlelabel3 = gtk_label_new (_("Ajout d'un nouveau Utilisateur"));
  gtk_widget_show (titlelabel3);
  gtk_fixed_put (GTK_FIXED (FX2), titlelabel3, 328, 72);
  gtk_widget_set_size_request (titlelabel3, 216, 24);

  txtentrynom = gtk_entry_new ();
  gtk_widget_show (txtentrynom);
  gtk_fixed_put (GTK_FIXED (FX2), txtentrynom, 384, 120);
  gtk_widget_set_size_request (txtentrynom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (txtentrynom), 8226);

  txtentryprenom = gtk_entry_new ();
  gtk_widget_show (txtentryprenom);
  gtk_fixed_put (GTK_FIXED (FX2), txtentryprenom, 384, 160);
  gtk_widget_set_size_request (txtentryprenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (txtentryprenom), 8226);

  labelnom = gtk_label_new (_("Nom :"));
  gtk_widget_show (labelnom);
  gtk_fixed_put (GTK_FIXED (FX2), labelnom, 288, 128);
  gtk_widget_set_size_request (labelnom, 73, 16);

  labelprenom = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (labelprenom);
  gtk_fixed_put (GTK_FIXED (FX2), labelprenom, 288, 168);
  gtk_widget_set_size_request (labelprenom, 73, 16);

  spinbuttonj_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonj_adj), 1, 0);
  gtk_widget_show (spinbuttonj);
  gtk_fixed_put (GTK_FIXED (FX2), spinbuttonj, 328, 240);
  gtk_widget_set_size_request (spinbuttonj, 60, 27);

  spinbuttonm_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonm = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonm_adj), 1, 0);
  gtk_widget_show (spinbuttonm);
  gtk_fixed_put (GTK_FIXED (FX2), spinbuttonm, 408, 240);
  gtk_widget_set_size_request (spinbuttonm, 60, 27);

  txtentrycin = gtk_entry_new ();
  gtk_widget_show (txtentrycin);
  gtk_fixed_put (GTK_FIXED (FX2), txtentrycin, 384, 336);
  gtk_widget_set_size_request (txtentrycin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (txtentrycin), 8226);

  txtentryid = gtk_entry_new ();
  gtk_widget_show (txtentryid);
  gtk_fixed_put (GTK_FIXED (FX2), txtentryid, 384, 376);
  gtk_widget_set_size_request (txtentryid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (txtentryid), 8226);

  labelid = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (labelid);
  gtk_fixed_put (GTK_FIXED (FX2), labelid, 232, 384);
  gtk_widget_set_size_request (labelid, 177, 16);

  txtentrypass = gtk_entry_new ();
  gtk_widget_show (txtentrypass);
  gtk_fixed_put (GTK_FIXED (FX2), txtentrypass, 384, 416);
  gtk_widget_set_size_request (txtentrypass, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (txtentrypass), 8226);

  labelcin = gtk_label_new (_("Num\303\251ro de CIN :"));
  gtk_widget_show (labelcin);
  gtk_fixed_put (GTK_FIXED (FX2), labelcin, 232, 344);
  gtk_widget_set_size_request (labelcin, 177, 16);

  labelpass = gtk_label_new (_("Mot de passe :"));
  gtk_widget_show (labelpass);
  gtk_fixed_put (GTK_FIXED (FX2), labelpass, 232, 424);
  gtk_widget_set_size_request (labelpass, 177, 16);

  labelvote = gtk_label_new (_("Vote :"));
  gtk_widget_show (labelvote);
  gtk_fixed_put (GTK_FIXED (FX2), labelvote, 224, 464);
  gtk_widget_set_size_request (labelvote, 177, 16);

  txtentrybv = gtk_entry_new ();
  gtk_widget_show (txtentrybv);
  gtk_fixed_put (GTK_FIXED (FX2), txtentrybv, 632, 360);
  gtk_widget_set_size_request (txtentrybv, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (txtentrybv), 8226);

  labelbv = gtk_label_new (_("Num\303\251ro de bureau de vote :"));
  gtk_widget_show (labelbv);
  gtk_fixed_put (GTK_FIXED (FX2), labelbv, 608, 336);
  gtk_widget_set_size_request (labelbv, 209, 16);

  labeltp = gtk_label_new (_("Type :"));
  gtk_widget_show (labeltp);
  gtk_fixed_put (GTK_FIXED (FX2), labeltp, 608, 400);
  gtk_widget_set_size_request (labeltp, 209, 16);

  labeldn = gtk_label_new (_("Date de Naissance :"));
  gtk_widget_show (labeldn);
  gtk_fixed_put (GTK_FIXED (FX2), labeldn, 240, 208);
  gtk_widget_set_size_request (labeldn, 177, 16);

  labelgender = gtk_label_new (_("Gender :"));
  gtk_widget_show (labelgender);
  gtk_fixed_put (GTK_FIXED (FX2), labelgender, 240, 288);
  gtk_widget_set_size_request (labelgender, 121, 16);

  labeltitleaj = gtk_label_new (_("Gestion des Utilisateurs"));
  gtk_widget_show (labeltitleaj);
  gtk_fixed_put (GTK_FIXED (FX2), labeltitleaj, 328, 48);
  gtk_widget_set_size_request (labeltitleaj, 216, 24);

  comboboxannee = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxannee);
  gtk_fixed_put (GTK_FIXED (FX2), comboboxannee, 488, 240);
  gtk_widget_set_size_request (comboboxannee, 80, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("2004"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("2003"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("2002"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("2001"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("2000"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1999"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1998"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1997"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1996"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1995"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1994"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1993"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1992"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1991"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1990"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1989"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1988"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1987"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1986"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1985"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1984"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1983"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1982"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1981"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1980"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1979"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1978"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1977"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1976"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1975"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1974"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1973"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1972"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1971"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1970"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1969"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1968"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1967"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1966"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1965"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1964"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1963"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1962"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1961"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1960"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1959"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1958"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1957"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1956"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1955"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1954"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1953"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1952"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1951"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1950"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1949"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1948"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1947"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1946"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1945"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1944"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1943"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1942"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1941"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxannee), _("1940"));

  comboboxtypeuts = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxtypeuts);
  gtk_fixed_put (GTK_FIXED (FX2), comboboxtypeuts, 632, 432);
  gtk_widget_set_size_request (comboboxtypeuts, 160, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxtypeuts), _("Admin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxtypeuts), _("Electeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxtypeuts), _("Observateur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxtypeuts), _("AgentBV"));

  radiobuttonf = gtk_radio_button_new_with_mnemonic (NULL, _("F"));
  gtk_widget_show (radiobuttonf);
  gtk_fixed_put (GTK_FIXED (FX2), radiobuttonf, 456, 296);
  gtk_widget_set_size_request (radiobuttonf, 56, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonf), radiobuttonf_group);
  radiobuttonf_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonf));

  radiobuttonm = gtk_radio_button_new_with_mnemonic (NULL, _("M"));
  gtk_widget_show (radiobuttonm);
  gtk_fixed_put (GTK_FIXED (FX2), radiobuttonm, 384, 296);
  gtk_widget_set_size_request (radiobuttonm, 56, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonm), radiobuttonf_group);
  radiobuttonf_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonm));

  checkbtn = gtk_check_button_new_with_mnemonic (_("J'ai lu et j'accepte les conditions d'utilisation."));
  gtk_widget_show (checkbtn);
  gtk_fixed_put (GTK_FIXED (FX2), checkbtn, 312, 504);
  gtk_widget_set_size_request (checkbtn, 336, 24);

  boutonconfirmeraj = gtk_button_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (boutonconfirmeraj);
  gtk_fixed_put (GTK_FIXED (FX2), boutonconfirmeraj, 688, 496);
  gtk_widget_set_size_request (boutonconfirmeraj, 90, 29);

  boutonrtraj = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (boutonrtraj);
  gtk_fixed_put (GTK_FIXED (FX2), boutonrtraj, 72, 152);
  gtk_widget_set_size_request (boutonrtraj, 90, 29);

  casevote = gtk_label_new (_("-1"));
  gtk_widget_show (casevote);
  gtk_fixed_put (GTK_FIXED (FX2), casevote, 376, 456);
  gtk_widget_set_size_request (casevote, 137, 33);

  checkbtnlabel = gtk_label_new ("");
  gtk_widget_show (checkbtnlabel);
  gtk_fixed_put (GTK_FIXED (FX2), checkbtnlabel, 16, 504);
  gtk_widget_set_size_request (checkbtnlabel, 296, 24);

  g_signal_connect ((gpointer) radiobuttonf, "toggled",
                    G_CALLBACK (on_radiobuttonf_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonm, "toggled",
                    G_CALLBACK (on_radiobuttonm_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbtn, "toggled",
                    G_CALLBACK (on_checkbtn_toggled),
                    NULL);
  g_signal_connect ((gpointer) boutonconfirmeraj, "clicked",
                    G_CALLBACK (on_boutonconfirmeraj_clicked),
                    NULL);
  g_signal_connect ((gpointer) boutonrtraj, "clicked",
                    G_CALLBACK (on_boutonrtraj_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GDU2, GDU2, "GDU2");
  GLADE_HOOKUP_OBJECT (GDU2, FX2, "FX2");
  GLADE_HOOKUP_OBJECT (GDU2, titlelabel3, "titlelabel3");
  GLADE_HOOKUP_OBJECT (GDU2, txtentrynom, "txtentrynom");
  GLADE_HOOKUP_OBJECT (GDU2, txtentryprenom, "txtentryprenom");
  GLADE_HOOKUP_OBJECT (GDU2, labelnom, "labelnom");
  GLADE_HOOKUP_OBJECT (GDU2, labelprenom, "labelprenom");
  GLADE_HOOKUP_OBJECT (GDU2, spinbuttonj, "spinbuttonj");
  GLADE_HOOKUP_OBJECT (GDU2, spinbuttonm, "spinbuttonm");
  GLADE_HOOKUP_OBJECT (GDU2, txtentrycin, "txtentrycin");
  GLADE_HOOKUP_OBJECT (GDU2, txtentryid, "txtentryid");
  GLADE_HOOKUP_OBJECT (GDU2, labelid, "labelid");
  GLADE_HOOKUP_OBJECT (GDU2, txtentrypass, "txtentrypass");
  GLADE_HOOKUP_OBJECT (GDU2, labelcin, "labelcin");
  GLADE_HOOKUP_OBJECT (GDU2, labelpass, "labelpass");
  GLADE_HOOKUP_OBJECT (GDU2, labelvote, "labelvote");
  GLADE_HOOKUP_OBJECT (GDU2, txtentrybv, "txtentrybv");
  GLADE_HOOKUP_OBJECT (GDU2, labelbv, "labelbv");
  GLADE_HOOKUP_OBJECT (GDU2, labeltp, "labeltp");
  GLADE_HOOKUP_OBJECT (GDU2, labeldn, "labeldn");
  GLADE_HOOKUP_OBJECT (GDU2, labelgender, "labelgender");
  GLADE_HOOKUP_OBJECT (GDU2, labeltitleaj, "labeltitleaj");
  GLADE_HOOKUP_OBJECT (GDU2, comboboxannee, "comboboxannee");
  GLADE_HOOKUP_OBJECT (GDU2, comboboxtypeuts, "comboboxtypeuts");
  GLADE_HOOKUP_OBJECT (GDU2, radiobuttonf, "radiobuttonf");
  GLADE_HOOKUP_OBJECT (GDU2, radiobuttonm, "radiobuttonm");
  GLADE_HOOKUP_OBJECT (GDU2, checkbtn, "checkbtn");
  GLADE_HOOKUP_OBJECT (GDU2, boutonconfirmeraj, "boutonconfirmeraj");
  GLADE_HOOKUP_OBJECT (GDU2, boutonrtraj, "boutonrtraj");
  GLADE_HOOKUP_OBJECT (GDU2, casevote, "casevote");
  GLADE_HOOKUP_OBJECT (GDU2, checkbtnlabel, "checkbtnlabel");

  return GDU2;
}

GtkWidget*
create_GDU4 (void)
{
  GtkWidget *GDU4;
  GtkWidget *FX4;
  GtkWidget *labeltitlegsuppr;
  GtkWidget *labeltitlesuppr;
  GtkWidget *labeltitlecin;
  GtkWidget *txtentrycinn;
  GtkWidget *btnrtrsuppr;
  GtkWidget *boutoncfrsuppr;
  GtkWidget *labelconfsupp;

  GDU4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GDU4), _("Gestion Des Utilisateurs"));

  FX4 = gtk_fixed_new ();
  gtk_widget_show (FX4);
  gtk_container_add (GTK_CONTAINER (GDU4), FX4);

  labeltitlegsuppr = gtk_label_new (_("Gestion des Utilisateurs"));
  gtk_widget_show (labeltitlegsuppr);
  gtk_fixed_put (GTK_FIXED (FX4), labeltitlegsuppr, 280, 64);
  gtk_widget_set_size_request (labeltitlegsuppr, 185, 16);

  labeltitlesuppr = gtk_label_new (_("Suppression des Utilisateurs"));
  gtk_widget_show (labeltitlesuppr);
  gtk_fixed_put (GTK_FIXED (FX4), labeltitlesuppr, 256, 88);
  gtk_widget_set_size_request (labeltitlesuppr, 225, 24);

  labeltitlecin = gtk_label_new (_("Num\303\251ro de CIN :"));
  gtk_widget_show (labeltitlecin);
  gtk_fixed_put (GTK_FIXED (FX4), labeltitlecin, 176, 144);
  gtk_widget_set_size_request (labeltitlecin, 161, 40);

  txtentrycinn = gtk_entry_new ();
  gtk_widget_show (txtentrycinn);
  gtk_fixed_put (GTK_FIXED (FX4), txtentrycinn, 288, 200);
  gtk_widget_set_size_request (txtentrycinn, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (txtentrycinn), 8226);

  btnrtrsuppr = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (btnrtrsuppr);
  gtk_fixed_put (GTK_FIXED (FX4), btnrtrsuppr, 40, 464);
  gtk_widget_set_size_request (btnrtrsuppr, 106, 48);

  boutoncfrsuppr = gtk_button_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (boutoncfrsuppr);
  gtk_fixed_put (GTK_FIXED (FX4), boutoncfrsuppr, 312, 264);
  gtk_widget_set_size_request (boutoncfrsuppr, 106, 48);

  labelconfsupp = gtk_label_new ("");
  gtk_widget_show (labelconfsupp);
  gtk_fixed_put (GTK_FIXED (FX4), labelconfsupp, 256, 336);
  gtk_widget_set_size_request (labelconfsupp, 224, 40);

  g_signal_connect ((gpointer) btnrtrsuppr, "clicked",
                    G_CALLBACK (on_btnrtrsuppr_clicked),
                    NULL);
  g_signal_connect ((gpointer) boutoncfrsuppr, "clicked",
                    G_CALLBACK (on_boutoncfrsuppr_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GDU4, GDU4, "GDU4");
  GLADE_HOOKUP_OBJECT (GDU4, FX4, "FX4");
  GLADE_HOOKUP_OBJECT (GDU4, labeltitlegsuppr, "labeltitlegsuppr");
  GLADE_HOOKUP_OBJECT (GDU4, labeltitlesuppr, "labeltitlesuppr");
  GLADE_HOOKUP_OBJECT (GDU4, labeltitlecin, "labeltitlecin");
  GLADE_HOOKUP_OBJECT (GDU4, txtentrycinn, "txtentrycinn");
  GLADE_HOOKUP_OBJECT (GDU4, btnrtrsuppr, "btnrtrsuppr");
  GLADE_HOOKUP_OBJECT (GDU4, boutoncfrsuppr, "boutoncfrsuppr");
  GLADE_HOOKUP_OBJECT (GDU4, labelconfsupp, "labelconfsupp");

  return GDU4;
}

GtkWidget*
create_GDU3 (void)
{
  GtkWidget *GDU3;
  GtkWidget *FX3;
  GtkWidget *txtentrynommodif;
  GtkWidget *txtentryprenommodif;
  GtkWidget *labelprenommodif;
  GtkObject *spinbuttonjmodif_adj;
  GtkWidget *spinbuttonjmodif;
  GtkWidget *comboboxanmodif;
  GtkObject *spinbuttonmmodif_adj;
  GtkWidget *spinbuttonmmodif;
  GtkWidget *txtentrycinmodif;
  GtkWidget *radiobuttonmmodif;
  GSList *radiobuttonmmodif_group = NULL;
  GtkWidget *radiobuttonfmodif;
  GSList *radiobuttonfmodif_group = NULL;
  GtkWidget *txtentryidmodif;
  GtkWidget *txtentrypassmodif;
  GtkWidget *txtentrybvmodif;
  GtkWidget *labelbvmodif;
  GtkWidget *labeltpmodif;
  GtkWidget *comboboxtpmodif;
  GtkWidget *labeldnmodif;
  GtkWidget *labelgendermodif;
  GtkWidget *txtviewvotemodif;
  GtkWidget *labelnommodif;
  GtkWidget *labeltitlemodif;
  GtkWidget *labeltitlemodif2;
  GtkWidget *labelcinmodif;
  GtkWidget *boutonconfmodif;
  GtkWidget *boutonrtrmodif;
  GtkWidget *boutonrecherchermodif;
  GtkWidget *labelidmodif;
  GtkWidget *labelpassmodif;
  GtkWidget *labelvotemodif;

  GDU3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GDU3), _("Gestion Des Utilisateurs"));

  FX3 = gtk_fixed_new ();
  gtk_widget_show (FX3);
  gtk_container_add (GTK_CONTAINER (GDU3), FX3);

  txtentrynommodif = gtk_entry_new ();
  gtk_widget_show (txtentrynommodif);
  gtk_fixed_put (GTK_FIXED (FX3), txtentrynommodif, 384, 120);
  gtk_widget_set_size_request (txtentrynommodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (txtentrynommodif), 8226);

  txtentryprenommodif = gtk_entry_new ();
  gtk_widget_show (txtentryprenommodif);
  gtk_fixed_put (GTK_FIXED (FX3), txtentryprenommodif, 384, 160);
  gtk_widget_set_size_request (txtentryprenommodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (txtentryprenommodif), 8226);

  labelprenommodif = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (labelprenommodif);
  gtk_fixed_put (GTK_FIXED (FX3), labelprenommodif, 288, 168);
  gtk_widget_set_size_request (labelprenommodif, 73, 16);

  spinbuttonjmodif_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonjmodif = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonjmodif_adj), 1, 0);
  gtk_widget_show (spinbuttonjmodif);
  gtk_fixed_put (GTK_FIXED (FX3), spinbuttonjmodif, 328, 240);
  gtk_widget_set_size_request (spinbuttonjmodif, 60, 27);

  comboboxanmodif = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxanmodif);
  gtk_fixed_put (GTK_FIXED (FX3), comboboxanmodif, 488, 240);
  gtk_widget_set_size_request (comboboxanmodif, 77, 32);

  spinbuttonmmodif_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonmmodif = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmmodif_adj), 1, 0);
  gtk_widget_show (spinbuttonmmodif);
  gtk_fixed_put (GTK_FIXED (FX3), spinbuttonmmodif, 408, 240);
  gtk_widget_set_size_request (spinbuttonmmodif, 60, 27);

  txtentrycinmodif = gtk_entry_new ();
  gtk_widget_show (txtentrycinmodif);
  gtk_fixed_put (GTK_FIXED (FX3), txtentrycinmodif, 64, 72);
  gtk_widget_set_size_request (txtentrycinmodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (txtentrycinmodif), 8226);

  radiobuttonmmodif = gtk_radio_button_new_with_mnemonic (NULL, _("M"));
  gtk_widget_show (radiobuttonmmodif);
  gtk_fixed_put (GTK_FIXED (FX3), radiobuttonmmodif, 384, 296);
  gtk_widget_set_size_request (radiobuttonmmodif, 56, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonmmodif), radiobuttonmmodif_group);
  radiobuttonmmodif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonmmodif));

  radiobuttonfmodif = gtk_radio_button_new_with_mnemonic (NULL, _("F"));
  gtk_widget_show (radiobuttonfmodif);
  gtk_fixed_put (GTK_FIXED (FX3), radiobuttonfmodif, 456, 296);
  gtk_widget_set_size_request (radiobuttonfmodif, 56, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonfmodif), radiobuttonfmodif_group);
  radiobuttonfmodif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonfmodif));

  txtentryidmodif = gtk_entry_new ();
  gtk_widget_show (txtentryidmodif);
  gtk_fixed_put (GTK_FIXED (FX3), txtentryidmodif, 384, 344);
  gtk_widget_set_size_request (txtentryidmodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (txtentryidmodif), 8226);

  txtentrypassmodif = gtk_entry_new ();
  gtk_widget_show (txtentrypassmodif);
  gtk_fixed_put (GTK_FIXED (FX3), txtentrypassmodif, 384, 392);
  gtk_widget_set_size_request (txtentrypassmodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (txtentrypassmodif), 8226);

  txtentrybvmodif = gtk_entry_new ();
  gtk_widget_show (txtentrybvmodif);
  gtk_fixed_put (GTK_FIXED (FX3), txtentrybvmodif, 632, 360);
  gtk_widget_set_size_request (txtentrybvmodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (txtentrybvmodif), 8226);

  labelbvmodif = gtk_label_new (_("Num\303\251ro de bureau de vote :"));
  gtk_widget_show (labelbvmodif);
  gtk_fixed_put (GTK_FIXED (FX3), labelbvmodif, 608, 336);
  gtk_widget_set_size_request (labelbvmodif, 209, 16);

  labeltpmodif = gtk_label_new (_("Type :"));
  gtk_widget_show (labeltpmodif);
  gtk_fixed_put (GTK_FIXED (FX3), labeltpmodif, 608, 400);
  gtk_widget_set_size_request (labeltpmodif, 209, 16);

  comboboxtpmodif = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxtpmodif);
  gtk_fixed_put (GTK_FIXED (FX3), comboboxtpmodif, 640, 424);
  gtk_widget_set_size_request (comboboxtpmodif, 149, 32);

  labeldnmodif = gtk_label_new (_("Date de Naissance :"));
  gtk_widget_show (labeldnmodif);
  gtk_fixed_put (GTK_FIXED (FX3), labeldnmodif, 240, 208);
  gtk_widget_set_size_request (labeldnmodif, 177, 16);

  labelgendermodif = gtk_label_new (_("Gender :"));
  gtk_widget_show (labelgendermodif);
  gtk_fixed_put (GTK_FIXED (FX3), labelgendermodif, 240, 288);
  gtk_widget_set_size_request (labelgendermodif, 121, 16);

  txtviewvotemodif = gtk_text_view_new ();
  gtk_widget_show (txtviewvotemodif);
  gtk_fixed_put (GTK_FIXED (FX3), txtviewvotemodif, 384, 440);
  gtk_widget_set_size_request (txtviewvotemodif, 160, 24);
  gtk_text_view_set_justification (GTK_TEXT_VIEW (txtviewvotemodif), GTK_JUSTIFY_CENTER);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (txtviewvotemodif)), _("-1"), -1);

  labelnommodif = gtk_label_new (_("Nom :"));
  gtk_widget_show (labelnommodif);
  gtk_fixed_put (GTK_FIXED (FX3), labelnommodif, 288, 128);
  gtk_widget_set_size_request (labelnommodif, 73, 16);

  labeltitlemodif = gtk_label_new (_("Modification des donn\303\251es de l'utilisateur"));
  gtk_widget_show (labeltitlemodif);
  gtk_fixed_put (GTK_FIXED (FX3), labeltitlemodif, 328, 72);
  gtk_widget_set_size_request (labeltitlemodif, 280, 24);

  labeltitlemodif2 = gtk_label_new (_("Gestion des Utilisateurs"));
  gtk_widget_show (labeltitlemodif2);
  gtk_fixed_put (GTK_FIXED (FX3), labeltitlemodif2, 352, 48);
  gtk_widget_set_size_request (labeltitlemodif2, 216, 24);

  labelcinmodif = gtk_label_new (_("Num\303\251ro de CIN :"));
  gtk_widget_show (labelcinmodif);
  gtk_fixed_put (GTK_FIXED (FX3), labelcinmodif, 56, 40);
  gtk_widget_set_size_request (labelcinmodif, 177, 16);

  boutonconfmodif = gtk_button_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (boutonconfmodif);
  gtk_fixed_put (GTK_FIXED (FX3), boutonconfmodif, 744, 496);
  gtk_widget_set_size_request (boutonconfmodif, 90, 29);

  boutonrtrmodif = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (boutonrtrmodif);
  gtk_fixed_put (GTK_FIXED (FX3), boutonrtrmodif, 640, 496);
  gtk_widget_set_size_request (boutonrtrmodif, 90, 29);

  boutonrecherchermodif = gtk_button_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (boutonrecherchermodif);
  gtk_fixed_put (GTK_FIXED (FX3), boutonrecherchermodif, 96, 112);
  gtk_widget_set_size_request (boutonrecherchermodif, 90, 29);

  labelidmodif = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (labelidmodif);
  gtk_fixed_put (GTK_FIXED (FX3), labelidmodif, 232, 352);
  gtk_widget_set_size_request (labelidmodif, 177, 16);

  labelpassmodif = gtk_label_new (_("Mot de passe :"));
  gtk_widget_show (labelpassmodif);
  gtk_fixed_put (GTK_FIXED (FX3), labelpassmodif, 232, 400);
  gtk_widget_set_size_request (labelpassmodif, 177, 16);

  labelvotemodif = gtk_label_new (_("Vote :"));
  gtk_widget_show (labelvotemodif);
  gtk_fixed_put (GTK_FIXED (FX3), labelvotemodif, 224, 440);
  gtk_widget_set_size_request (labelvotemodif, 177, 16);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GDU3, GDU3, "GDU3");
  GLADE_HOOKUP_OBJECT (GDU3, FX3, "FX3");
  GLADE_HOOKUP_OBJECT (GDU3, txtentrynommodif, "txtentrynommodif");
  GLADE_HOOKUP_OBJECT (GDU3, txtentryprenommodif, "txtentryprenommodif");
  GLADE_HOOKUP_OBJECT (GDU3, labelprenommodif, "labelprenommodif");
  GLADE_HOOKUP_OBJECT (GDU3, spinbuttonjmodif, "spinbuttonjmodif");
  GLADE_HOOKUP_OBJECT (GDU3, comboboxanmodif, "comboboxanmodif");
  GLADE_HOOKUP_OBJECT (GDU3, spinbuttonmmodif, "spinbuttonmmodif");
  GLADE_HOOKUP_OBJECT (GDU3, txtentrycinmodif, "txtentrycinmodif");
  GLADE_HOOKUP_OBJECT (GDU3, radiobuttonmmodif, "radiobuttonmmodif");
  GLADE_HOOKUP_OBJECT (GDU3, radiobuttonfmodif, "radiobuttonfmodif");
  GLADE_HOOKUP_OBJECT (GDU3, txtentryidmodif, "txtentryidmodif");
  GLADE_HOOKUP_OBJECT (GDU3, txtentrypassmodif, "txtentrypassmodif");
  GLADE_HOOKUP_OBJECT (GDU3, txtentrybvmodif, "txtentrybvmodif");
  GLADE_HOOKUP_OBJECT (GDU3, labelbvmodif, "labelbvmodif");
  GLADE_HOOKUP_OBJECT (GDU3, labeltpmodif, "labeltpmodif");
  GLADE_HOOKUP_OBJECT (GDU3, comboboxtpmodif, "comboboxtpmodif");
  GLADE_HOOKUP_OBJECT (GDU3, labeldnmodif, "labeldnmodif");
  GLADE_HOOKUP_OBJECT (GDU3, labelgendermodif, "labelgendermodif");
  GLADE_HOOKUP_OBJECT (GDU3, txtviewvotemodif, "txtviewvotemodif");
  GLADE_HOOKUP_OBJECT (GDU3, labelnommodif, "labelnommodif");
  GLADE_HOOKUP_OBJECT (GDU3, labeltitlemodif, "labeltitlemodif");
  GLADE_HOOKUP_OBJECT (GDU3, labeltitlemodif2, "labeltitlemodif2");
  GLADE_HOOKUP_OBJECT (GDU3, labelcinmodif, "labelcinmodif");
  GLADE_HOOKUP_OBJECT (GDU3, boutonconfmodif, "boutonconfmodif");
  GLADE_HOOKUP_OBJECT (GDU3, boutonrtrmodif, "boutonrtrmodif");
  GLADE_HOOKUP_OBJECT (GDU3, boutonrecherchermodif, "boutonrecherchermodif");
  GLADE_HOOKUP_OBJECT (GDU3, labelidmodif, "labelidmodif");
  GLADE_HOOKUP_OBJECT (GDU3, labelpassmodif, "labelpassmodif");
  GLADE_HOOKUP_OBJECT (GDU3, labelvotemodif, "labelvotemodif");

  return GDU3;
}

