/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_GDU1 (void);
GtkWidget* create_GDU2 (void);
GtkWidget* create_GDU4 (void);
GtkWidget* create_GDU3 (void);
GtkWidget* create_GDU5 (void);
GtkWidget* create_GDU6 (void);
