/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Statistique_ (void)
{
  GtkWidget *Statistique_;
  GtkWidget *fixed1;
  GtkWidget *entrySTAT5;
  GtkWidget *labelSTAT6;
  GtkWidget *labelSTAT5;
  GtkWidget *labelSTAT3;
  GtkWidget *labelSTAT2;
  GtkWidget *labelSTAT1;
  GtkWidget *labelSTAT4;
  GtkWidget *labelSTAT7;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *labelTITRE;
  GtkWidget *buttonSTAT1;
  GtkWidget *buttonSTAT2;
  GtkWidget *buttonSTAT3;
  GtkWidget *buttonSTAT4;
  GtkWidget *buttonSTAT5;
  GtkWidget *buttonSTAT6;
  GtkWidget *buttonretourSTAT;
  GtkWidget *image1;

  Statistique_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Statistique_), _("Statistique"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Statistique_), fixed1);

  entrySTAT5 = gtk_entry_new ();
  gtk_widget_show (entrySTAT5);
  gtk_fixed_put (GTK_FIXED (fixed1), entrySTAT5, 72, 440);
  gtk_widget_set_size_request (entrySTAT5, 168, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrySTAT5), 8226);

  labelSTAT6 = gtk_label_new ("");
  gtk_widget_show (labelSTAT6);
  gtk_fixed_put (GTK_FIXED (fixed1), labelSTAT6, 384, 440);
  gtk_widget_set_size_request (labelSTAT6, 144, 32);

  labelSTAT5 = gtk_label_new (_("\n:: Le nombre du electeur par bureau  de vote  ::\n***Entrer le numero du bureau de vote ***\n"));
  gtk_widget_show (labelSTAT5);
  gtk_fixed_put (GTK_FIXED (fixed1), labelSTAT5, 32, 352);
  gtk_widget_set_size_request (labelSTAT5, 368, 56);

  labelSTAT3 = gtk_label_new ("");
  gtk_widget_show (labelSTAT3);
  gtk_fixed_put (GTK_FIXED (fixed1), labelSTAT3, 328, 216);
  gtk_widget_set_size_request (labelSTAT3, 112, 32);

  labelSTAT2 = gtk_label_new ("");
  gtk_widget_show (labelSTAT2);
  gtk_fixed_put (GTK_FIXED (fixed1), labelSTAT2, 416, 144);
  gtk_widget_set_size_request (labelSTAT2, 144, 32);

  labelSTAT1 = gtk_label_new ("");
  gtk_widget_show (labelSTAT1);
  gtk_fixed_put (GTK_FIXED (fixed1), labelSTAT1, 368, 72);
  gtk_widget_set_size_request (labelSTAT1, 160, 32);

  labelSTAT4 = gtk_label_new ("");
  gtk_widget_show (labelSTAT4);
  gtk_fixed_put (GTK_FIXED (fixed1), labelSTAT4, 352, 296);
  gtk_widget_set_size_request (labelSTAT4, 152, 32);

  labelSTAT7 = gtk_label_new ("");
  gtk_widget_show (labelSTAT7);
  gtk_fixed_put (GTK_FIXED (fixed1), labelSTAT7, 344, 512);
  gtk_widget_set_size_request (labelSTAT7, 160, 32);

  label8 = gtk_label_new ("");
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 264, 24);
  gtk_widget_set_size_request (label8, 80, 16);

  label9 = gtk_label_new ("");
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 320, 24);
  gtk_widget_set_size_request (label9, 41, 17);

  labelTITRE = gtk_label_new (_("TABLEAU DE BORD"));
  gtk_widget_show (labelTITRE);
  gtk_fixed_put (GTK_FIXED (fixed1), labelTITRE, 216, 16);
  gtk_widget_set_size_request (labelTITRE, 216, 32);

  buttonSTAT1 = gtk_button_new_with_mnemonic (_("Le taux de participation des electeurs"));
  gtk_widget_show (buttonSTAT1);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonSTAT1, 40, 64);
  gtk_widget_set_size_request (buttonSTAT1, 272, 40);

  buttonSTAT2 = gtk_button_new_with_mnemonic (_("Le taux de participation deshommes et des femmes "));
  gtk_widget_show (buttonSTAT2);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonSTAT2, 40, 136);
  gtk_widget_set_size_request (buttonSTAT2, 360, 40);

  buttonSTAT3 = gtk_button_new_with_mnemonic (_("Le taux de votes blancs"));
  gtk_widget_show (buttonSTAT3);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonSTAT3, 40, 208);
  gtk_widget_set_size_request (buttonSTAT3, 232, 40);

  buttonSTAT4 = gtk_button_new_with_mnemonic (_("L'age moyen des electeurs participants "));
  gtk_widget_show (buttonSTAT4);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonSTAT4, 40, 288);
  gtk_widget_set_size_request (buttonSTAT4, 288, 40);

  buttonSTAT5 = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (buttonSTAT5);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonSTAT5, 264, 440);
  gtk_widget_set_size_request (buttonSTAT5, 66, 29);

  buttonSTAT6 = gtk_button_new_with_mnemonic (_("Nombre total  de reclamations"));
  gtk_widget_show (buttonSTAT6);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonSTAT6, 48, 504);
  gtk_widget_set_size_request (buttonSTAT6, 256, 40);

  buttonretourSTAT = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (buttonretourSTAT);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonretourSTAT, 16, 616);
  gtk_widget_set_size_request (buttonretourSTAT, 128, 32);

  image1 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 24, 624);
  gtk_widget_set_size_request (image1, 21, 21);

  g_signal_connect ((gpointer) buttonSTAT1, "clicked",
                    G_CALLBACK (on_buttonSTAT1_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSTAT2, "clicked",
                    G_CALLBACK (on_buttonSTAT2_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSTAT3, "clicked",
                    G_CALLBACK (on_buttonSTAT3_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSTAT4, "clicked",
                    G_CALLBACK (on_buttonSTAT4_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSTAT5, "clicked",
                    G_CALLBACK (on_buttonSTAT5_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSTAT6, "clicked",
                    G_CALLBACK (on_buttonSTAT6_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourSTAT, "clicked",
                    G_CALLBACK (on_buttonretourSTAT_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Statistique_, Statistique_, "Statistique_");
  GLADE_HOOKUP_OBJECT (Statistique_, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Statistique_, entrySTAT5, "entrySTAT5");
  GLADE_HOOKUP_OBJECT (Statistique_, labelSTAT6, "labelSTAT6");
  GLADE_HOOKUP_OBJECT (Statistique_, labelSTAT5, "labelSTAT5");
  GLADE_HOOKUP_OBJECT (Statistique_, labelSTAT3, "labelSTAT3");
  GLADE_HOOKUP_OBJECT (Statistique_, labelSTAT2, "labelSTAT2");
  GLADE_HOOKUP_OBJECT (Statistique_, labelSTAT1, "labelSTAT1");
  GLADE_HOOKUP_OBJECT (Statistique_, labelSTAT4, "labelSTAT4");
  GLADE_HOOKUP_OBJECT (Statistique_, labelSTAT7, "labelSTAT7");
  GLADE_HOOKUP_OBJECT (Statistique_, label8, "label8");
  GLADE_HOOKUP_OBJECT (Statistique_, label9, "label9");
  GLADE_HOOKUP_OBJECT (Statistique_, labelTITRE, "labelTITRE");
  GLADE_HOOKUP_OBJECT (Statistique_, buttonSTAT1, "buttonSTAT1");
  GLADE_HOOKUP_OBJECT (Statistique_, buttonSTAT2, "buttonSTAT2");
  GLADE_HOOKUP_OBJECT (Statistique_, buttonSTAT3, "buttonSTAT3");
  GLADE_HOOKUP_OBJECT (Statistique_, buttonSTAT4, "buttonSTAT4");
  GLADE_HOOKUP_OBJECT (Statistique_, buttonSTAT5, "buttonSTAT5");
  GLADE_HOOKUP_OBJECT (Statistique_, buttonSTAT6, "buttonSTAT6");
  GLADE_HOOKUP_OBJECT (Statistique_, buttonretourSTAT, "buttonretourSTAT");
  GLADE_HOOKUP_OBJECT (Statistique_, image1, "image1");

  return Statistique_;
}

