/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_shs (void)
{
  GtkWidget *shs;
  GtkWidget *fixed1;
  GtkWidget *lbl1;
  GtkWidget *entr1;
  GtkObject *entr2_adj;
  GtkWidget *entr2;
  GtkWidget *lbl3;
  GtkWidget *lbl2;
  GtkWidget *lbl4;
  GtkWidget *rdb1;
  GSList *rdb1_group = NULL;
  GtkWidget *rdb2;
  GtkWidget *rdb3;
  GtkWidget *btn1;

  shs = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (shs), _("Somme_Heures_supp"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (shs), fixed1);

  lbl1 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (lbl1);
  gtk_fixed_put (GTK_FIXED (fixed1), lbl1, 32, 48);
  gtk_widget_set_size_request (lbl1, 112, 16);

  entr1 = gtk_entry_new ();
  gtk_widget_show (entr1);
  gtk_fixed_put (GTK_FIXED (fixed1), entr1, 144, 40);
  gtk_widget_set_size_request (entr1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entr1), 8226);

  entr2_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  entr2 = gtk_spin_button_new (GTK_ADJUSTMENT (entr2_adj), 1, 0);
  gtk_widget_show (entr2);
  gtk_fixed_put (GTK_FIXED (fixed1), entr2, 160, 88);
  gtk_widget_set_size_request (entr2, 60, 27);

  lbl3 = gtk_label_new (_("Prix :"));
  gtk_widget_show (lbl3);
  gtk_fixed_put (GTK_FIXED (fixed1), lbl3, 56, 136);
  gtk_widget_set_size_request (lbl3, 57, 25);

  lbl2 = gtk_label_new (_("Nombre heures :"));
  gtk_widget_show (lbl2);
  gtk_fixed_put (GTK_FIXED (fixed1), lbl2, 24, 88);
  gtk_widget_set_size_request (lbl2, 136, 24);

  lbl4 = gtk_label_new (_("somme : "));
  gtk_widget_show (lbl4);
  gtk_fixed_put (GTK_FIXED (fixed1), lbl4, 184, 272);
  gtk_widget_set_size_request (lbl4, 208, 24);

  rdb1 = gtk_radio_button_new_with_mnemonic (NULL, _("15"));
  gtk_widget_show (rdb1);
  gtk_fixed_put (GTK_FIXED (fixed1), rdb1, 64, 176);
  gtk_widget_set_size_request (rdb1, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rdb1), rdb1_group);
  rdb1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rdb1));

  rdb2 = gtk_radio_button_new_with_mnemonic (NULL, _("20"));
  gtk_widget_show (rdb2);
  gtk_fixed_put (GTK_FIXED (fixed1), rdb2, 168, 176);
  gtk_widget_set_size_request (rdb2, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rdb2), rdb1_group);
  rdb1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rdb2));

  rdb3 = gtk_radio_button_new_with_mnemonic (NULL, _("30"));
  gtk_widget_show (rdb3);
  gtk_fixed_put (GTK_FIXED (fixed1), rdb3, 288, 176);
  gtk_widget_set_size_request (rdb3, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rdb3), rdb1_group);
  rdb1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rdb3));

  btn1 = gtk_button_new_with_mnemonic (_("Calculer"));
  gtk_widget_show (btn1);
  gtk_fixed_put (GTK_FIXED (fixed1), btn1, 152, 224);
  gtk_widget_set_size_request (btn1, 96, 40);

  g_signal_connect ((gpointer) rdb1, "toggled",
                    G_CALLBACK (on_rdb1_toggled),
                    NULL);
  g_signal_connect ((gpointer) rdb2, "toggled",
                    G_CALLBACK (on_rdb2_toggled),
                    NULL);
  g_signal_connect ((gpointer) rdb3, "toggled",
                    G_CALLBACK (on_rdb3_toggled),
                    NULL);
  g_signal_connect ((gpointer) btn1, "clicked",
                    G_CALLBACK (on_btn1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (shs, shs, "shs");
  GLADE_HOOKUP_OBJECT (shs, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (shs, lbl1, "lbl1");
  GLADE_HOOKUP_OBJECT (shs, entr1, "entr1");
  GLADE_HOOKUP_OBJECT (shs, entr2, "entr2");
  GLADE_HOOKUP_OBJECT (shs, lbl3, "lbl3");
  GLADE_HOOKUP_OBJECT (shs, lbl2, "lbl2");
  GLADE_HOOKUP_OBJECT (shs, lbl4, "lbl4");
  GLADE_HOOKUP_OBJECT (shs, rdb1, "rdb1");
  GLADE_HOOKUP_OBJECT (shs, rdb2, "rdb2");
  GLADE_HOOKUP_OBJECT (shs, rdb3, "rdb3");
  GLADE_HOOKUP_OBJECT (shs, btn1, "btn1");

  return shs;
}

