/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_GDU1 (void);
GtkWidget* create_GDU2 (void);
GtkWidget* create_GDU4 (void);
GtkWidget* create_GDU3 (void);
GtkWidget* create_GDU5 (void);
GtkWidget* create_GDU6 (void);
GtkWidget* create_GDU7 (void);
GtkWidget* create_GDU8 (void);
GtkWidget* create_GDU9 (void);
GtkWidget* create_GDU10 (void);
GtkWidget* create_af (void);
GtkWidget* create_aj (void);
GtkWidget* create_mod (void);
GtkWidget* create_mariem_1 (void);
GtkWidget* create_gestion_des_reclamations (void);
GtkWidget* create_ajouter_une_reclamation (void);
GtkWidget* create_modifier_une_reclamation (void);
GtkWidget* create_supprimer_une_reclamation (void);
GtkWidget* create_mariem2 (void);
GtkWidget* create_mariem3 (void);
GtkWidget* create_mariem_4 (void);
GtkWidget* create_Ajouter_fatma (void);
GtkWidget* create_Modifier_fatma (void);
GtkWidget* create_afficher_fatma (void);
GtkWidget* create_supprimer_fatma (void);
