/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mariem_1 (void)
{
  GtkWidget *mariem_1;
  GtkWidget *fixed1MM;
  GtkWidget *treeview1MM;
  GtkWidget *label1MM;
  GtkWidget *button2MM;
  GtkWidget *image12;
  GtkWidget *button3modtreeMM;
  GtkWidget *image2;
  GtkWidget *button4supptreeMM;
  GtkWidget *image3;
  GtkWidget *buttonactualiserMM;
  GtkWidget *image13;
  GtkWidget *vscrollbar1;
  GtkWidget *button1MM;
  GtkWidget *image4;
  GtkWidget *label2MM;

  mariem_1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mariem_1), _("affichage bureaux du votes"));

  fixed1MM = gtk_fixed_new ();
  gtk_widget_show (fixed1MM);
  gtk_container_add (GTK_CONTAINER (mariem_1), fixed1MM);

  treeview1MM = gtk_tree_view_new ();
  gtk_widget_show (treeview1MM);
  gtk_fixed_put (GTK_FIXED (fixed1MM), treeview1MM, 80, 136);
  gtk_widget_set_size_request (treeview1MM, 1216, 488);

  label1MM = gtk_label_new (_("gestion des bureaux du votes"));
  gtk_widget_show (label1MM);
  gtk_fixed_put (GTK_FIXED (fixed1MM), label1MM, 568, 8);
  gtk_widget_set_size_request (label1MM, 304, 48);

  button2MM = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (button2MM);
  gtk_fixed_put (GTK_FIXED (fixed1MM), button2MM, 1360, 224);
  gtk_widget_set_size_request (button2MM, 144, 40);

  image12 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed1MM), image12, 1376, 232);
  gtk_widget_set_size_request (image12, 24, 24);

  button3modtreeMM = gtk_button_new_with_mnemonic (_("modifier "));
  gtk_widget_show (button3modtreeMM);
  gtk_fixed_put (GTK_FIXED (fixed1MM), button3modtreeMM, 1360, 304);
  gtk_widget_set_size_request (button3modtreeMM, 144, 40);

  image2 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed1MM), image2, 1368, 312);
  gtk_widget_set_size_request (image2, 32, 24);

  button4supptreeMM = gtk_button_new_with_mnemonic (_("supprimer "));
  gtk_widget_show (button4supptreeMM);
  gtk_fixed_put (GTK_FIXED (fixed1MM), button4supptreeMM, 1360, 392);
  gtk_widget_set_size_request (button4supptreeMM, 144, 40);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_fixed_put (GTK_FIXED (fixed1MM), image3, 1360, 400);
  gtk_widget_set_size_request (image3, 32, 24);

  buttonactualiserMM = gtk_button_new_with_mnemonic (_("actualiser"));
  gtk_widget_show (buttonactualiserMM);
  gtk_fixed_put (GTK_FIXED (fixed1MM), buttonactualiserMM, 1360, 488);
  gtk_widget_set_size_request (buttonactualiserMM, 144, 40);

  image13 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed1MM), image13, 1368, 496);
  gtk_widget_set_size_request (image13, 32, 24);

  vscrollbar1 = gtk_vscrollbar_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 0, 0, 0, 0)));
  gtk_widget_show (vscrollbar1);
  gtk_fixed_put (GTK_FIXED (fixed1MM), vscrollbar1, 1296, 160);
  gtk_widget_set_size_request (vscrollbar1, 16, 464);

  button1MM = gtk_button_new_with_mnemonic (_("retour "));
  gtk_widget_show (button1MM);
  gtk_fixed_put (GTK_FIXED (fixed1MM), button1MM, 80, 696);
  gtk_widget_set_size_request (button1MM, 128, 40);

  image4 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_fixed_put (GTK_FIXED (fixed1MM), image4, 96, 704);
  gtk_widget_set_size_request (image4, 24, 24);

  label2MM = gtk_label_new (_("LIste des bureaux du votes"));
  gtk_widget_show (label2MM);
  gtk_fixed_put (GTK_FIXED (fixed1MM), label2MM, 592, 8);
  gtk_widget_set_size_request (label2MM, 256, 144);

  g_signal_connect ((gpointer) button2MM, "clicked",
                    G_CALLBACK (on_button2MM_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3modtreeMM, "clicked",
                    G_CALLBACK (on_button3modtreeMM_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4supptreeMM, "clicked",
                    G_CALLBACK (on_button4supptreeMM_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonactualiserMM, "clicked",
                    G_CALLBACK (on_buttonactualiserMM_clicked),
                    NULL);
  g_signal_connect ((gpointer) vscrollbar1, "adjust_bounds",
                    G_CALLBACK (on_vscrollbar1_adjust_bounds),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mariem_1, mariem_1, "mariem_1");
  GLADE_HOOKUP_OBJECT (mariem_1, fixed1MM, "fixed1MM");
  GLADE_HOOKUP_OBJECT (mariem_1, treeview1MM, "treeview1MM");
  GLADE_HOOKUP_OBJECT (mariem_1, label1MM, "label1MM");
  GLADE_HOOKUP_OBJECT (mariem_1, button2MM, "button2MM");
  GLADE_HOOKUP_OBJECT (mariem_1, image12, "image12");
  GLADE_HOOKUP_OBJECT (mariem_1, button3modtreeMM, "button3modtreeMM");
  GLADE_HOOKUP_OBJECT (mariem_1, image2, "image2");
  GLADE_HOOKUP_OBJECT (mariem_1, button4supptreeMM, "button4supptreeMM");
  GLADE_HOOKUP_OBJECT (mariem_1, image3, "image3");
  GLADE_HOOKUP_OBJECT (mariem_1, buttonactualiserMM, "buttonactualiserMM");
  GLADE_HOOKUP_OBJECT (mariem_1, image13, "image13");
  GLADE_HOOKUP_OBJECT (mariem_1, vscrollbar1, "vscrollbar1");
  GLADE_HOOKUP_OBJECT (mariem_1, button1MM, "button1MM");
  GLADE_HOOKUP_OBJECT (mariem_1, image4, "image4");
  GLADE_HOOKUP_OBJECT (mariem_1, label2MM, "label2MM");

  return mariem_1;
}

GtkWidget*
create_mariem2 (void)
{
  GtkWidget *mariem2;
  GtkWidget *fixed2MM;
  GtkWidget *entry1MM;
  GtkWidget *entry2MM;
  GtkWidget *label6;
  GtkObject *spinbutton1MM_adj;
  GtkWidget *spinbutton1MM;
  GtkWidget *entry3MM;
  GtkWidget *button6MM;
  GtkWidget *image5;
  GtkWidget *button5MM;
  GtkWidget *image6;
  GtkWidget *radiobutton1MM;
  GSList *radiobutton1MM_group = NULL;
  GtkWidget *radiobutton2MM;
  GtkWidget *combobox4MM;
  GtkWidget *entrycapobMM;
  GtkWidget *label4MM;
  GtkWidget *label5MM;
  GtkWidget *label7MM;
  GtkWidget *label8MM;
  GtkWidget *label9MM;
  GtkWidget *label10MM;
  GtkWidget *label11MM;
  GtkWidget *label3MM;
  GtkWidget *labelmsgMM;

  mariem2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mariem2), _("ajout bureau de vote"));

  fixed2MM = gtk_fixed_new ();
  gtk_widget_show (fixed2MM);
  gtk_container_add (GTK_CONTAINER (mariem2), fixed2MM);

  entry1MM = gtk_entry_new ();
  gtk_widget_show (entry1MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), entry1MM, 184, 144);
  gtk_widget_set_size_request (entry1MM, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1MM), 8226);

  entry2MM = gtk_entry_new ();
  gtk_widget_show (entry2MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), entry2MM, 184, 208);
  gtk_widget_set_size_request (entry2MM, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2MM), 8226);

  label6 = gtk_label_new ("");
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label6, 24, 144);
  gtk_widget_set_size_request (label6, 41, 17);

  spinbutton1MM_adj = gtk_adjustment_new (1, 1, 5, 1, 10, 10);
  spinbutton1MM = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1MM_adj), 1, 0);
  gtk_widget_show (spinbutton1MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), spinbutton1MM, 232, 512);
  gtk_widget_set_size_request (spinbutton1MM, 60, 27);

  entry3MM = gtk_entry_new ();
  gtk_widget_show (entry3MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), entry3MM, 184, 296);
  gtk_widget_set_size_request (entry3MM, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3MM), 8226);

  button6MM = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (button6MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), button6MM, 8, 752);
  gtk_widget_set_size_request (button6MM, 120, 40);

  image5 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_fixed_put (GTK_FIXED (fixed2MM), image5, 16, 760);
  gtk_widget_set_size_request (image5, 24, 24);

  button5MM = gtk_button_new_with_mnemonic (_("confirmer "));
  gtk_widget_show (button5MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), button5MM, 848, 752);
  gtk_widget_set_size_request (button5MM, 120, 40);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_fixed_put (GTK_FIXED (fixed2MM), image6, 848, 760);
  gtk_widget_set_size_request (image6, 37, 29);

  radiobutton1MM = gtk_radio_button_new_with_mnemonic (NULL, _("disponible "));
  gtk_widget_show (radiobutton1MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), radiobutton1MM, 168, 608);
  gtk_widget_set_size_request (radiobutton1MM, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1MM), radiobutton1MM_group);
  radiobutton1MM_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1MM));

  radiobutton2MM = gtk_radio_button_new_with_mnemonic (NULL, _("non disponible "));
  gtk_widget_show (radiobutton2MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), radiobutton2MM, 328, 608);
  gtk_widget_set_size_request (radiobutton2MM, 144, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2MM), radiobutton1MM_group);
  radiobutton1MM_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2MM));

  combobox4MM = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), combobox4MM, 168, 672);
  gtk_widget_set_size_request (combobox4MM, 184, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4MM), _("1234456AG"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4MM), _("3458351AG"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4MM), _("9804326AG"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4MM), _("2265410AG"));

  entrycapobMM = gtk_entry_new ();
  gtk_widget_show (entrycapobMM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), entrycapobMM, 192, 384);
  gtk_widget_set_size_request (entrycapobMM, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycapobMM), 8226);

  label4MM = gtk_label_new (_("Numero du bureau"));
  gtk_widget_show (label4MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label4MM, 32, 144);
  gtk_widget_set_size_request (label4MM, 144, 24);

  label5MM = gtk_label_new (_("Adresse"));
  gtk_widget_show (label5MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label5MM, 24, 208);
  gtk_widget_set_size_request (label5MM, 96, 32);

  label7MM = gtk_label_new (_("Capacite electeur"));
  gtk_widget_show (label7MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label7MM, 24, 296);
  gtk_widget_set_size_request (label7MM, 128, 32);

  label8MM = gtk_label_new (_("Capacite observateur "));
  gtk_widget_show (label8MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label8MM, 8, 384);
  gtk_widget_set_size_request (label8MM, 192, 32);

  label9MM = gtk_label_new (_("Nombre des salles"));
  gtk_widget_show (label9MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label9MM, 24, 512);
  gtk_widget_set_size_request (label9MM, 136, 24);

  label10MM = gtk_label_new (_("Etat des salles "));
  gtk_widget_show (label10MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label10MM, 24, 608);
  gtk_widget_set_size_request (label10MM, 128, 16);

  label11MM = gtk_label_new (_("ID agent "));
  gtk_widget_show (label11MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label11MM, 24, 672);
  gtk_widget_set_size_request (label11MM, 88, 32);

  label3MM = gtk_label_new (_("Ajout d'un nouveau bureau du vote"));
  gtk_widget_show (label3MM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), label3MM, 304, 40);
  gtk_widget_set_size_request (label3MM, 296, 40);

  labelmsgMM = gtk_label_new ("");
  gtk_widget_show (labelmsgMM);
  gtk_fixed_put (GTK_FIXED (fixed2MM), labelmsgMM, 368, 720);
  gtk_widget_set_size_request (labelmsgMM, 456, 32);

  g_signal_connect ((gpointer) button6MM, "clicked",
                    G_CALLBACK (on_button6MM_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5MM, "clicked",
                    G_CALLBACK (on_button5MM_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1MM, "toggled",
                    G_CALLBACK (on_radiobutton1MM_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2MM, "toggled",
                    G_CALLBACK (on_radiobutton2MM_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mariem2, mariem2, "mariem2");
  GLADE_HOOKUP_OBJECT (mariem2, fixed2MM, "fixed2MM");
  GLADE_HOOKUP_OBJECT (mariem2, entry1MM, "entry1MM");
  GLADE_HOOKUP_OBJECT (mariem2, entry2MM, "entry2MM");
  GLADE_HOOKUP_OBJECT (mariem2, label6, "label6");
  GLADE_HOOKUP_OBJECT (mariem2, spinbutton1MM, "spinbutton1MM");
  GLADE_HOOKUP_OBJECT (mariem2, entry3MM, "entry3MM");
  GLADE_HOOKUP_OBJECT (mariem2, button6MM, "button6MM");
  GLADE_HOOKUP_OBJECT (mariem2, image5, "image5");
  GLADE_HOOKUP_OBJECT (mariem2, button5MM, "button5MM");
  GLADE_HOOKUP_OBJECT (mariem2, image6, "image6");
  GLADE_HOOKUP_OBJECT (mariem2, radiobutton1MM, "radiobutton1MM");
  GLADE_HOOKUP_OBJECT (mariem2, radiobutton2MM, "radiobutton2MM");
  GLADE_HOOKUP_OBJECT (mariem2, combobox4MM, "combobox4MM");
  GLADE_HOOKUP_OBJECT (mariem2, entrycapobMM, "entrycapobMM");
  GLADE_HOOKUP_OBJECT (mariem2, label4MM, "label4MM");
  GLADE_HOOKUP_OBJECT (mariem2, label5MM, "label5MM");
  GLADE_HOOKUP_OBJECT (mariem2, label7MM, "label7MM");
  GLADE_HOOKUP_OBJECT (mariem2, label8MM, "label8MM");
  GLADE_HOOKUP_OBJECT (mariem2, label9MM, "label9MM");
  GLADE_HOOKUP_OBJECT (mariem2, label10MM, "label10MM");
  GLADE_HOOKUP_OBJECT (mariem2, label11MM, "label11MM");
  GLADE_HOOKUP_OBJECT (mariem2, label3MM, "label3MM");
  GLADE_HOOKUP_OBJECT (mariem2, labelmsgMM, "labelmsgMM");

  return mariem2;
}

GtkWidget*
create_mariem3 (void)
{
  GtkWidget *mariem3;
  GtkWidget *fixed3MM;
  GtkWidget *fixed4MM;
  GtkWidget *entry4MM;
  GtkWidget *entry5MM;
  GtkWidget *label12;
  GtkObject *spinbutton2MM_adj;
  GtkWidget *spinbutton2MM;
  GtkWidget *entry6MM;
  GtkWidget *label15msgMM;
  GtkWidget *button7MM;
  GtkWidget *image8;
  GtkWidget *label18MM;
  GtkWidget *combobox4MM;
  GtkWidget *radiobutton3MM;
  GSList *radiobutton3MM_group = NULL;
  GtkWidget *radiobutton4MM;
  GtkWidget *button9MM;
  GtkWidget *image9;
  GtkWidget *label19MM;
  GtkWidget *label20MM;
  GtkWidget *label13MM;
  GtkWidget *label23MM;
  GtkWidget *label16MM;
  GtkWidget *label17MM;
  GtkWidget *entry1;
  GtkWidget *label14msgmodf;
  GtkWidget *label13msgreche;
  GtkWidget *button8MM;
  GtkWidget *image7;
  GtkWidget *label55MM;

  mariem3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mariem3), _("modification bureau du vote"));

  fixed3MM = gtk_fixed_new ();
  gtk_widget_show (fixed3MM);
  gtk_container_add (GTK_CONTAINER (mariem3), fixed3MM);

  fixed4MM = gtk_fixed_new ();
  gtk_widget_show (fixed4MM);
  gtk_fixed_put (GTK_FIXED (fixed3MM), fixed4MM, 48, 0);
  gtk_widget_set_size_request (fixed4MM, 256, 40);

  entry4MM = gtk_entry_new ();
  gtk_widget_show (entry4MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), entry4MM, 168, 200);
  gtk_widget_set_size_request (entry4MM, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4MM), 8226);

  entry5MM = gtk_entry_new ();
  gtk_widget_show (entry5MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), entry5MM, 168, 280);
  gtk_widget_set_size_request (entry5MM, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5MM), 8226);

  label12 = gtk_label_new ("");
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label12, 24, 144);
  gtk_widget_set_size_request (label12, 41, 17);

  spinbutton2MM_adj = gtk_adjustment_new (4, 1, 5, 1, 10, 10);
  spinbutton2MM = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2MM_adj), 1, 0);
  gtk_widget_show (spinbutton2MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), spinbutton2MM, 232, 552);
  gtk_widget_set_size_request (spinbutton2MM, 60, 27);

  entry6MM = gtk_entry_new ();
  gtk_widget_show (entry6MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), entry6MM, 168, 360);
  gtk_widget_set_size_request (entry6MM, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6MM), 8226);

  label15msgMM = gtk_label_new ("");
  gtk_widget_show (label15msgMM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label15msgMM, 272, 416);
  gtk_widget_set_size_request (label15msgMM, 376, 32);

  button7MM = gtk_button_new_with_mnemonic (_("confirmer "));
  gtk_widget_show (button7MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), button7MM, 736, 792);
  gtk_widget_set_size_request (button7MM, 160, 40);

  image8 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_fixed_put (GTK_FIXED (fixed4MM), image8, 760, 800);
  gtk_widget_set_size_request (image8, 16, 24);

  label18MM = gtk_label_new (_("ID agent "));
  gtk_widget_show (label18MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label18MM, 24, 712);
  gtk_widget_set_size_request (label18MM, 72, 16);

  combobox4MM = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), combobox4MM, 152, 704);
  gtk_widget_set_size_request (combobox4MM, 200, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4MM), _("1234456AG"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4MM), _("3458351AG"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4MM), _("9804326AG"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4MM), _("2265410AG"));

  radiobutton3MM = gtk_radio_button_new_with_mnemonic (NULL, _("disponible "));
  gtk_widget_show (radiobutton3MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), radiobutton3MM, 168, 632);
  gtk_widget_set_size_request (radiobutton3MM, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3MM), radiobutton3MM_group);
  radiobutton3MM_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3MM));

  radiobutton4MM = gtk_radio_button_new_with_mnemonic (NULL, _("non disponible "));
  gtk_widget_show (radiobutton4MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), radiobutton4MM, 320, 632);
  gtk_widget_set_size_request (radiobutton4MM, 136, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4MM), radiobutton3MM_group);
  radiobutton3MM_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4MM));

  button9MM = gtk_button_new_with_mnemonic (_("rechercher "));
  gtk_widget_show (button9MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), button9MM, 408, 200);
  gtk_widget_set_size_request (button9MM, 144, 24);

  image9 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_fixed_put (GTK_FIXED (fixed4MM), image9, 408, 200);
  gtk_widget_set_size_request (image9, 32, 24);

  label19MM = gtk_label_new (_("Modification d'un bureau du vote"));
  gtk_widget_show (label19MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label19MM, 256, 8);
  gtk_widget_set_size_request (label19MM, 256, 24);

  label20MM = gtk_label_new (_("Numero du bureau"));
  gtk_widget_show (label20MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label20MM, 0, 200);
  gtk_widget_set_size_request (label20MM, 136, 16);

  label13MM = gtk_label_new (_("Adresse"));
  gtk_widget_show (label13MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label13MM, 0, 288);
  gtk_widget_set_size_request (label13MM, 88, 16);

  label23MM = gtk_label_new (_("Capacite electeur"));
  gtk_widget_show (label23MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label23MM, 8, 368);
  gtk_widget_set_size_request (label23MM, 136, 16);

  label16MM = gtk_label_new (_("Capacite observateur "));
  gtk_widget_show (label16MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label16MM, 0, 456);
  gtk_widget_set_size_request (label16MM, 168, 24);

  label17MM = gtk_label_new (_("Etat des salles "));
  gtk_widget_show (label17MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label17MM, 8, 640);
  gtk_widget_set_size_request (label17MM, 128, 16);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed4MM), entry1, 168, 456);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  label14msgmodf = gtk_label_new ("");
  gtk_widget_show (label14msgmodf);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label14msgmodf, 320, 792);
  gtk_widget_set_size_request (label14msgmodf, 336, 32);

  label13msgreche = gtk_label_new ("");
  gtk_widget_show (label13msgreche);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label13msgreche, 632, 200);
  gtk_widget_set_size_request (label13msgreche, 256, 24);

  button8MM = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (button8MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), button8MM, 0, 800);
  gtk_widget_set_size_request (button8MM, 136, 40);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed4MM), image7, 8, 808);
  gtk_widget_set_size_request (image7, 24, 24);

  label55MM = gtk_label_new (_("Nombre des salles"));
  gtk_widget_show (label55MM);
  gtk_fixed_put (GTK_FIXED (fixed4MM), label55MM, 16, 552);
  gtk_widget_set_size_request (label55MM, 120, 16);

  g_signal_connect ((gpointer) button7MM, "clicked",
                    G_CALLBACK (on_button7MM_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3MM, "toggled",
                    G_CALLBACK (on_radiobutton3MM_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4MM, "toggled",
                    G_CALLBACK (on_radiobutton4MM_toggled),
                    NULL);
  g_signal_connect ((gpointer) button9MM, "clicked",
                    G_CALLBACK (on_button9MM_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8MM, "clicked",
                    G_CALLBACK (on_button8MM_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mariem3, mariem3, "mariem3");
  GLADE_HOOKUP_OBJECT (mariem3, fixed3MM, "fixed3MM");
  GLADE_HOOKUP_OBJECT (mariem3, fixed4MM, "fixed4MM");
  GLADE_HOOKUP_OBJECT (mariem3, entry4MM, "entry4MM");
  GLADE_HOOKUP_OBJECT (mariem3, entry5MM, "entry5MM");
  GLADE_HOOKUP_OBJECT (mariem3, label12, "label12");
  GLADE_HOOKUP_OBJECT (mariem3, spinbutton2MM, "spinbutton2MM");
  GLADE_HOOKUP_OBJECT (mariem3, entry6MM, "entry6MM");
  GLADE_HOOKUP_OBJECT (mariem3, label15msgMM, "label15msgMM");
  GLADE_HOOKUP_OBJECT (mariem3, button7MM, "button7MM");
  GLADE_HOOKUP_OBJECT (mariem3, image8, "image8");
  GLADE_HOOKUP_OBJECT (mariem3, label18MM, "label18MM");
  GLADE_HOOKUP_OBJECT (mariem3, combobox4MM, "combobox4MM");
  GLADE_HOOKUP_OBJECT (mariem3, radiobutton3MM, "radiobutton3MM");
  GLADE_HOOKUP_OBJECT (mariem3, radiobutton4MM, "radiobutton4MM");
  GLADE_HOOKUP_OBJECT (mariem3, button9MM, "button9MM");
  GLADE_HOOKUP_OBJECT (mariem3, image9, "image9");
  GLADE_HOOKUP_OBJECT (mariem3, label19MM, "label19MM");
  GLADE_HOOKUP_OBJECT (mariem3, label20MM, "label20MM");
  GLADE_HOOKUP_OBJECT (mariem3, label13MM, "label13MM");
  GLADE_HOOKUP_OBJECT (mariem3, label23MM, "label23MM");
  GLADE_HOOKUP_OBJECT (mariem3, label16MM, "label16MM");
  GLADE_HOOKUP_OBJECT (mariem3, label17MM, "label17MM");
  GLADE_HOOKUP_OBJECT (mariem3, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (mariem3, label14msgmodf, "label14msgmodf");
  GLADE_HOOKUP_OBJECT (mariem3, label13msgreche, "label13msgreche");
  GLADE_HOOKUP_OBJECT (mariem3, button8MM, "button8MM");
  GLADE_HOOKUP_OBJECT (mariem3, image7, "image7");
  GLADE_HOOKUP_OBJECT (mariem3, label55MM, "label55MM");

  return mariem3;
}

GtkWidget*
create_mariem_4 (void)
{
  GtkWidget *mariem_4;
  GtkWidget *fixed5MM;
  GtkWidget *entry8MM;
  GtkWidget *drawingarea1;
  GtkWidget *button11MM;
  GtkWidget *image11;
  GtkWidget *button10MM;
  GtkWidget *image10;
  GtkWidget *label21MM;
  GtkWidget *label22MM;
  GtkWidget *label15msgMM;
  GtkWidget *checkbutton1;

  mariem_4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mariem_4), _("suppression bureau du vote"));

  fixed5MM = gtk_fixed_new ();
  gtk_widget_show (fixed5MM);
  gtk_container_add (GTK_CONTAINER (mariem_4), fixed5MM);

  entry8MM = gtk_entry_new ();
  gtk_widget_show (entry8MM);
  gtk_fixed_put (GTK_FIXED (fixed5MM), entry8MM, 400, 168);
  gtk_widget_set_size_request (entry8MM, 296, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8MM), 8226);

  drawingarea1 = gtk_drawing_area_new ();
  gtk_widget_show (drawingarea1);
  gtk_fixed_put (GTK_FIXED (fixed5MM), drawingarea1, 1000, 128);
  gtk_widget_set_size_request (drawingarea1, 50, 50);

  button11MM = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (button11MM);
  gtk_fixed_put (GTK_FIXED (fixed5MM), button11MM, 48, 592);
  gtk_widget_set_size_request (button11MM, 104, 32);

  image11 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_fixed_put (GTK_FIXED (fixed5MM), image11, 48, 600);
  gtk_widget_set_size_request (image11, 24, 16);

  button10MM = gtk_button_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (button10MM);
  gtk_fixed_put (GTK_FIXED (fixed5MM), button10MM, 792, 288);
  gtk_widget_set_size_request (button10MM, 168, 40);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_fixed_put (GTK_FIXED (fixed5MM), image10, 784, 288);
  gtk_widget_set_size_request (image10, 56, 40);

  label21MM = gtk_label_new (_("Suppression  d'un bureau du vote "));
  gtk_widget_show (label21MM);
  gtk_fixed_put (GTK_FIXED (fixed5MM), label21MM, 392, 48);
  gtk_widget_set_size_request (label21MM, 288, 56);

  label22MM = gtk_label_new (_("Numero du bureau "));
  gtk_widget_show (label22MM);
  gtk_fixed_put (GTK_FIXED (fixed5MM), label22MM, 224, 152);
  gtk_widget_set_size_request (label22MM, 176, 72);

  label15msgMM = gtk_label_new ("");
  gtk_widget_show (label15msgMM);
  gtk_fixed_put (GTK_FIXED (fixed5MM), label15msgMM, 368, 320);
  gtk_widget_set_size_request (label15msgMM, 376, 56);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("I'm not a robot "));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed5MM), checkbutton1, 528, 224);
  gtk_widget_set_size_request (checkbutton1, 144, 32);

  g_signal_connect ((gpointer) button11MM, "clicked",
                    G_CALLBACK (on_button11MM_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10MM, "clicked",
                    G_CALLBACK (on_button10MM_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mariem_4, mariem_4, "mariem_4");
  GLADE_HOOKUP_OBJECT (mariem_4, fixed5MM, "fixed5MM");
  GLADE_HOOKUP_OBJECT (mariem_4, entry8MM, "entry8MM");
  GLADE_HOOKUP_OBJECT (mariem_4, drawingarea1, "drawingarea1");
  GLADE_HOOKUP_OBJECT (mariem_4, button11MM, "button11MM");
  GLADE_HOOKUP_OBJECT (mariem_4, image11, "image11");
  GLADE_HOOKUP_OBJECT (mariem_4, button10MM, "button10MM");
  GLADE_HOOKUP_OBJECT (mariem_4, image10, "image10");
  GLADE_HOOKUP_OBJECT (mariem_4, label21MM, "label21MM");
  GLADE_HOOKUP_OBJECT (mariem_4, label22MM, "label22MM");
  GLADE_HOOKUP_OBJECT (mariem_4, label15msgMM, "label15msgMM");
  GLADE_HOOKUP_OBJECT (mariem_4, checkbutton1, "checkbutton1");

  return mariem_4;
}

